// ═══════════════════════════════════════════════════════════
//  📚 DATA.JS — All static app data
//  English With Sebastian v3.0
// ═══════════════════════════════════════════════════════════

// ─── i18n TRANSLATIONS ───────────────────────────────────
const TRANSLATIONS = {
  en: {
    // Auth
    appTagline: '🔥 The English app that actually has a personality',
    loginTab: '👋 Log In', signupTab: '✨ Sign Up',
    userPlaceholder: '👤 Username', passPlaceholder: '🔒 Password',
    namePlaceholder: '😎 Your name', newUserPlaceholder: '🆔 Pick a username',
    newPassPlaceholder: '🔑 Password (min 8 chars)',
    loginBtn: "🚀 Let's Go!", signupBtn: '🎉 Create Account!',
    demoHint: 'Demo: <b>test</b> / <b>1234</b> — no excuses now',
    loginErr: '❌ Wrong credentials, genius.', regErr: 'Fill everything in properly, please!',
    userTaken: 'Username taken! Try another one.',
    weakPass: '🔒 Password needs 8+ chars, uppercase, lowercase & a number.',
    passStrWeak: 'Weak', passStrFair: 'Fair', passStrStrong: 'Strong',
    googleBtn: '🔐 Continue with Google', authOr: 'or',
    googleSigningIn: 'Opening Google sign-in…', googleError: 'Google sign-in failed. Try again.',
    googleNotConfigured: 'Google login is not configured yet. Add Supabase keys in supabase-config.js.',
    googlePopupBlocked: 'Popup blocked. Allow popups for this site, then try again.',
    // Topbar
    search: 'Search', toggleTheme: 'Toggle theme',
    // Nav
    navHome: 'Home', navGrammar: 'Grammar', navSounds: 'Sounds',
    navAI: 'AI Tutor', navProfile: 'Profile', navAbout: 'About',
    // Home
    homeHeroEyebrow: 'Your learning hub',
    homeHeroGreet: 'Hey,',
    homeHeroSub: 'Level up your English with lessons, games, and your AI tutor — all in one place.',
    homeHeroLevel: 'Level', homeHeroStreak: 'Day streak', homeHeroXP: 'Total XP',
    homeHeroCtaLearn: '▶ Continue learning',
    homeHeroCtaChallenge: '🎲 Daily challenge',
    homeHeroCtaAI: '🤖 Ask AI Tutor',
    dashTitle: 'Your progress',
    dashSubtitle: 'XP, streaks, lessons & quizzes at a glance',
    dashXP: 'Total XP',
    dashStreak: 'Day streak',
    dashLessons: 'Lessons done',
    dashQuizzes: 'Quiz statistics',
    dashQuizTaken: 'Quizzes taken',
    dashAvgAccuracy: 'Avg accuracy',
    dashBestScore: 'Best score',
    dashPerfects: 'Perfect runs',
    dashLevelProgress: 'Level progress',
    dashDailyProgress: 'Daily goal',
    dashCourseProgress: 'Course progress',
    dashOf: '{done} of {total}',
    dashToNext: '{n} XP to Level {lvl}',
    streakTitle: 'Start your streak today!', streakDesc: 'Complete a lesson to begin 🫡',
    streakActive: '🔥 {n}-day streak!', streakActiveDesc: 'Amazing! Keep it going!',
    dailyGoal: '📅 Daily Goal — 50 XP (you got this)',
    xpToday: '{n} XP earned today', xpGoal: '50 XP goal',
    dailyChallenge: 'Daily Challenge', dailyChallengeDesc: "Complete for +10 bonus XP! Don't be lazy 😤",
    dailyDone: '✅ Challenge Complete!', dailyDoneDesc: 'Come back tomorrow for a new one!',
    leaderboard: 'Leaderboard', leaderboardDesc: 'See how you rank this week',
    wordScramble: 'Word Scramble', wordScrambleDesc: 'Quick game to earn extra XP',
    // Grammar
    grammarTitle: '📖 Grammar Lab', grammarSub: 'Master English grammar — one rule at a time 💪',
    grammarSearch: 'Search grammar topics...',
    // Sounds
    soundsTitle: '🔊 Sound Lab', soundsSub: 'Hear it, feel it, speak it — pronunciation mastery 🎤',
    practiceTab: '🗣️ Practice', pairsTab: '👥 Pairs', twistersTab: '🌀 Twisters', difficultTab: '🎯 Sounds',
    hearBtn: '🔊 Hear it', slowBtn: '🐌 Slow', recordBtn: '🎤 Record',
    pairsNote: 'Click to hear the difference between confusable sounds! 👂',
    twistersNote: 'Practice these daily — your fluency will skyrocket! 🚀',
    difficultNote: 'Sounds that trip up Portuguese speakers 🇲🇿 — master these!',
    // AI
    aiName: 'Sebastian AI Tutor', aiSub: 'Ask me anything about English! Grammar, vocabulary, pronunciation...',
    aiOnline: 'Online now', clearChat: '🗑️ Clear chat',
    chatPlaceholder: 'Ask Sebastian anything...',
    aiMode: 'Mode', aiModeNormal: '💬 Normal', aiModeGrammar: '📝 Grammar Check', aiModePron: '🎤 Pronunciation',
    // Profile
    logoutBtn: '🚪 Log Out', dayStreak: 'Day Streak', totalXP: 'Total XP',
    correctAnswers: 'Correct Answers', lessonsDone: 'Lessons Done',
    achievements: '🎖️ Achievements', settings: '⚙️ Settings',
    darkLight: '🌓 Dark / Light Mode', toggle: 'Toggle',
    interfaceLang: '🌐 Interface Language', discoMode: '🕺 Disco Mode',
    konami: '🎮 Konami Code',
    // Quiz
    close: '✕', continue: 'Continue ›', seeResults: 'See Results 🏆',
    correct: '✅ Correct!', incorrect: '❌ Incorrect',
    backHome: '🏠 Back Home', tryAgain: '🔄 Try Again',
    // Game
    gameTitle: '🔤 Word Scramble Madness', submitBtn: '🎯 Submit!',
    surrenderBtn: '💀 Surrender', skipBtn: 'Skip this one (coward 😤)',
    // Toast messages
    toastDisco: '🕺 DISCO MODE! 🎉', toastDiscoOff: 'Disco off. Back to learning 📚',
    toastLight: '☀️ Light mode!', toastDark: '🌙 Dark mode!',
    toastHeart: '❤️ Heart regenerated!', toastAllDone: '🎓 All free lessons completed! You\'re a legend!',
    toastGameOver: '🎮 Game over! Score: {n} · +{n} XP!',
    toastKonami: '🎮 KONAMI CODE! +100 XP!! 🎉',
    // Premium
    premiumTitle: 'Go Premium!', premiumSub: 'Unlock everything and become an English legend.',
    premiumFeat1: 'All units — Phrasal Verbs, Idioms, Advanced',
    premiumFeat2: 'Infinite hearts — fail as many times as you need',
    premiumFeat3: 'Unlimited AI Tutor sessions',
    premiumFeat4: 'Exclusive badges to flex on the leaderboard',
    premiumBtn: '💳 Upgrade — $4.99/month', premiumSkip: 'Maybe when I get paid 💸',
    // About
    aboutTitle: 'About Sebastian', aboutRole: 'English Teacher · Translator · Interpreter',
    aboutLocation: '📍 Maputo / Matola, Mozambique',
    aboutBio: 'Final-year Translation & Interpretation student at Universidade Eduardo Mondlane, passionate educator, and certified English teacher with 4+ years of experience helping students unlock their potential.',
    aboutStats1: 'Years Teaching', aboutStats2: 'Students Taught', aboutStats3: 'Languages', aboutStats4: 'Lessons Created',
    aboutEducation: '🎓 Education', aboutExperience: '💼 Experience', aboutSkills: '⚡ Skills',
    aboutContact: '📬 Get in Touch', aboutDownloadCV: '📄 Download CV',
    certifications: '🏅 Certifications',
    // Level up
    levelUp: 'LEVEL UP!!! 🎉', levelUpText: 'You reached Level {n}!', letsGo: "LET'S GOOOO! 🚀",
    // Search
    searchPlaceholder: 'Search lessons, grammar, sounds...',
    searchEmpty: 'Start typing to search... 🔎', searchNone: 'Nothing found. Try different words 🤔',
    // Loading
    loadMsg0: 'Warming up your brain cells... 🧠',
    loadMsg1: 'Loading vocabulary banks... 📚',
    loadMsg2: 'Calibrating grammar engines... 📖',
    loadMsg3: 'Tuning pronunciation AI... 🎤',
    loadMsg4: 'Preparing your lessons... 🎯',
    loadMsg5: 'Almost there... ✨',
    // Leaderboard
    lbTitle: '🏆 Top Learners',
    // Unit badges
    free: '✓ Free', premium: '👑 Premium',
    // Misc
    noHearts: '❤️ No hearts left! Wait 5 min...', alreadyDone: '✅ Already done today! Come back tomorrow.',
    paymentSoon: '🚧 Payment coming soon — stay tuned!',
  },
  pt: {
    appTagline: '🔥 A app de inglês que tem personalidade de verdade',
    loginTab: '👋 Entrar', signupTab: '✨ Registar',
    userPlaceholder: '👤 Nome de utilizador', passPlaceholder: '🔒 Palavra-passe',
    namePlaceholder: '😎 O teu nome', newUserPlaceholder: '🆔 Escolhe um utilizador',
    newPassPlaceholder: '🔑 Palavra-passe (mín. 8 caracteres)',
    loginBtn: '🚀 Vamos Lá!', signupBtn: '🎉 Criar Conta!',
    demoHint: 'Demo: <b>test</b> / <b>1234</b> — sem desculpas agora',
    loginErr: '❌ Credenciais erradas, caro!', regErr: 'Preenche tudo correctamente, por favor!',
    userTaken: 'Utilizador já existe! Tenta outro.',
    weakPass: '🔒 A palavra-passe precisa de 8+ caracteres, maiúscula, minúscula e número.',
    passStrWeak: 'Fraca', passStrFair: 'Razoável', passStrStrong: 'Forte',
    googleBtn: '🔐 Continuar com Google', authOr: 'ou',
    googleSigningIn: 'A abrir o Google…', googleError: 'Falha no login Google. Tenta outra vez.',
    googleNotConfigured: 'Login Google ainda não está configurado. Adiciona as chaves em supabase-config.js.',
    googlePopupBlocked: 'Popup bloqueado. Permite popups neste site e tenta de novo.',
    search: 'Pesquisar', toggleTheme: 'Mudar tema',
    navHome: 'Início', navGrammar: 'Gramática', navSounds: 'Sons',
    navAI: 'IA Tutor', navProfile: 'Perfil', navAbout: 'Sobre',
    homeHeroEyebrow: 'O teu centro de estudo',
    homeHeroGreet: 'Olá,',
    homeHeroSub: 'Melhora o teu inglês com lições, jogos e o tutor IA — tudo num só lugar.',
    homeHeroLevel: 'Nível', homeHeroStreak: 'Dias seguidos', homeHeroXP: 'XP total',
    homeHeroCtaLearn: '▶ Continuar a aprender',
    homeHeroCtaChallenge: '🎲 Desafio diário',
    homeHeroCtaAI: '🤖 Perguntar à IA',
    dashTitle: 'O teu progresso',
    dashSubtitle: 'XP, séries, lições e quizzes num relance',
    dashXP: 'XP total',
    dashStreak: 'Dias seguidos',
    dashLessons: 'Lições feitas',
    dashQuizzes: 'Estatísticas de quiz',
    dashQuizTaken: 'Quizzes feitos',
    dashAvgAccuracy: 'Precisão média',
    dashBestScore: 'Melhor resultado',
    dashPerfects: 'Quizzes perfeitos',
    dashLevelProgress: 'Progresso de nível',
    dashDailyProgress: 'Meta diária',
    dashCourseProgress: 'Progresso do curso',
    dashOf: '{done} de {total}',
    dashToNext: '{n} XP para o Nível {lvl}',
    streakTitle: 'Começa a tua série hoje!', streakDesc: 'Completa uma lição para começar 🫡',
    streakActive: '🔥 Série de {n} dias!', streakActiveDesc: 'Incrível! Continua assim!',
    dailyGoal: '📅 Meta Diária — 50 XP (consegues)',
    xpToday: '{n} XP ganhos hoje', xpGoal: 'Meta: 50 XP',
    dailyChallenge: 'Desafio Diário', dailyChallengeDesc: 'Completa para +10 XP bónus! Não sejas preguiçoso 😤',
    dailyDone: '✅ Desafio Completo!', dailyDoneDesc: 'Volta amanhã para um novo desafio!',
    leaderboard: 'Classificação', leaderboardDesc: 'Vê como estás classificado esta semana',
    wordScramble: 'Palavras Baralhadas', wordScrambleDesc: 'Jogo rápido para ganhar XP extra',
    grammarTitle: '📖 Laboratório de Gramática', grammarSub: 'Domina a gramática inglesa — uma regra de cada vez 💪',
    grammarSearch: 'Pesquisar tópicos de gramática...',
    soundsTitle: '🔊 Laboratório de Sons', soundsSub: 'Ouve, sente, fala — domínio da pronúncia 🎤',
    practiceTab: '🗣️ Praticar', pairsTab: '👥 Pares', twistersTab: '🌀 Trava-línguas', difficultTab: '🎯 Sons',
    hearBtn: '🔊 Ouvir', slowBtn: '🐌 Devagar', recordBtn: '🎤 Gravar',
    pairsNote: 'Clica para ouvir a diferença entre sons confundíveis! 👂',
    twistersNote: 'Pratica estes diariamente — a tua fluência vai disparar! 🚀',
    difficultNote: 'Sons que dificultam os falantes de português 🇲🇿 — domina-os!',
    aiName: 'IA Tutora Sebastian', aiSub: 'Pergunta-me qualquer coisa sobre inglês! Gramática, vocabulário, pronúncia...',
    aiOnline: 'Online agora', clearChat: '🗑️ Limpar conversa',
    chatPlaceholder: 'Pergunta qualquer coisa ao Sebastian...',
    aiMode: 'Modo', aiModeNormal: '💬 Normal', aiModeGrammar: '📝 Correcção', aiModePron: '🎤 Pronúncia',
    logoutBtn: '🚪 Sair', dayStreak: 'Dias Consecutivos', totalXP: 'XP Total',
    correctAnswers: 'Respostas Correctas', lessonsDone: 'Lições Concluídas',
    achievements: '🎖️ Conquistas', settings: '⚙️ Configurações',
    darkLight: '🌓 Modo Escuro / Claro', toggle: 'Alternar',
    interfaceLang: '🌐 Idioma da Interface', discoMode: '🕺 Modo Discoteca',
    konami: '🎮 Código Konami',
    close: '✕', continue: 'Continuar ›', seeResults: 'Ver Resultados 🏆',
    correct: '✅ Correcto!', incorrect: '❌ Incorrecto',
    backHome: '🏠 Início', tryAgain: '🔄 Tentar Novamente',
    gameTitle: '🔤 Palavras Baralhadas', submitBtn: '🎯 Submeter!',
    surrenderBtn: '💀 Desistir', skipBtn: 'Saltar esta (cobarde 😤)',
    toastDisco: '🕺 MODO DISCOTECA! 🎉', toastDiscoOff: 'Discoteca desligada. Volta ao estudo 📚',
    toastLight: '☀️ Modo claro!', toastDark: '🌙 Modo escuro!',
    toastHeart: '❤️ Coração regenerado!', toastAllDone: '🎓 Todas as lições gratuitas concluídas! Eras uma lenda!',
    toastGameOver: '🎮 Jogo terminado! Pontuação: {n} · +{n} XP!',
    toastKonami: '🎮 CÓDIGO KONAMI! +100 XP!! 🎉',
    premiumTitle: 'Torna-te Premium!', premiumSub: 'Desbloqueia tudo e torna-te uma lenda do inglês.',
    premiumFeat1: 'Todas as unidades — Phrasal Verbs, Expressões, Avançado',
    premiumFeat2: 'Corações infinitos — falha quantas vezes precisares',
    premiumFeat3: 'Sessões ilimitadas com a IA Tutora',
    premiumFeat4: 'Distintivos exclusivos para mostrar na classificação',
    premiumBtn: '💳 Actualizar — $4.99/mês', premiumSkip: 'Talvez quando me pagarem 💸',
    aboutTitle: 'Sobre o Sebastian', aboutRole: 'Professor de Inglês · Tradutor · Intérprete',
    aboutLocation: '📍 Maputo / Matola, Moçambique',
    aboutBio: 'Estudante finalista em Tradução e Interpretação na Universidade Eduardo Mondlane, educador apaixonado e professor certificado de inglês com mais de 4 anos de experiência a ajudar estudantes a atingir o seu potencial.',
    aboutStats1: 'Anos de Ensino', aboutStats2: 'Estudantes', aboutStats3: 'Línguas', aboutStats4: 'Lições Criadas',
    aboutEducation: '🎓 Formação', aboutExperience: '💼 Experiência', aboutSkills: '⚡ Competências',
    aboutContact: '📬 Contacto', aboutDownloadCV: '📄 Descarregar CV',
    certifications: '🏅 Certificações',
    levelUp: 'SUBIU DE NÍVEL!!! 🎉', levelUpText: 'Chegaste ao Nível {n}!', letsGo: 'VAMOS LÁ! 🚀',
    searchPlaceholder: 'Pesquisar lições, gramática, sons...',
    searchEmpty: 'Começa a escrever para pesquisar... 🔎', searchNone: 'Nada encontrado. Tenta palavras diferentes 🤔',
    loadMsg0: 'A aquecer as células cerebrais... 🧠',
    loadMsg1: 'A carregar vocabulário... 📚',
    loadMsg2: 'A calibrar os motores de gramática... 📖',
    loadMsg3: 'A afinar a IA de pronúncia... 🎤',
    loadMsg4: 'A preparar as tuas lições... 🎯',
    loadMsg5: 'Quase lá... ✨',
    lbTitle: '🏆 Melhores Estudantes',
    free: '✓ Grátis', premium: '👑 Premium',
    noHearts: '❤️ Sem corações! Espera 5 min...', alreadyDone: '✅ Já concluído hoje! Volta amanhã.',
    paymentSoon: '🚧 Pagamento em breve — mantém-te atento!',
  },
  // ── Mozambican Portuguese (mz) — distinct flavour with local expressions ──
  mz: {
    appTagline: '🔥 A app de inglês que bate mesmo — feita em Moçambique 🇲🇿',
    loginTab: '👋 Entrar', signupTab: '✨ Registar',
    userPlaceholder: '👤 Nome de utilizador', passPlaceholder: '🔒 Palavra-passe',
    namePlaceholder: '😎 O teu nome', newUserPlaceholder: '🆔 Escolhe um nome',
    newPassPlaceholder: '🔑 Palavra-passe (mín. 8 caracteres)',
    loginBtn: '🚀 Vamos a isso!', signupBtn: '🎉 Criar Conta!',
    loginErr: '❌ Credenciais erradas, mano!', regErr: 'Preenche tudo direito, please!',
    userTaken: 'Este nome já existe! Tenta outro.',
    weakPass: '🔒 A palavra-passe precisa de 8+ caracteres, maiúscula, minúscula e número.',
    passStrWeak: 'Fraca', passStrFair: 'Razoável', passStrStrong: 'Forte',
    googleBtn: '🔐 Continuar com Google', authOr: 'ou',
    googleSigningIn: 'A abrir o Google…', googleError: 'Login Google falhou. Tenta outra vez.',
    googleNotConfigured: 'Login Google ainda não configurado. Adiciona as chaves em supabase-config.js.',
    googlePopupBlocked: 'Popup bloqueado. Permite popups neste site e tenta de novo.',
    search: 'Pesquisar', toggleTheme: 'Mudar tema',
    navHome: 'Início', navGrammar: 'Gramática', navSounds: 'Sons',
    navAI: 'IA Tutora', navProfile: 'Perfil', navAbout: 'Sobre',
    homeHeroEyebrow: 'O teu centro de aprendizagem',
    homeHeroGreet: 'Olá,',
    homeHeroSub: 'Melhora o teu inglês com lições, jogos e a tutora IA — tudo num só lugar, de graça.',
    homeHeroLevel: 'Nível', homeHeroStreak: 'Dias seguidos', homeHeroXP: 'XP total',
    homeHeroCtaLearn: '▶ Continuar a aprender',
    homeHeroCtaChallenge: '🎲 Desafio do dia',
    homeHeroCtaAI: '🤖 Perguntar à IA',
    dashTitle: 'O teu progresso',
    dashSubtitle: 'XP, séries, lições e quizzes de uma vez',
    dashXP: 'XP total',
    dashStreak: 'Dias seguidos',
    dashLessons: 'Lições feitas',
    dashQuizzes: 'Estatísticas de quiz',
    dashQuizTaken: 'Quizzes feitos',
    dashAvgAccuracy: 'Precisão média',
    dashBestScore: 'Melhor resultado',
    dashPerfects: 'Quizzes perfeitos',
    dashLevelProgress: 'Progresso de nível',
    dashDailyProgress: 'Meta diária',
    dashCourseProgress: 'Progresso do curso',
    dashOf: '{done} de {total}',
    dashToNext: '{n} XP para o Nível {lvl}',
    streakTitle: 'Começa a tua série hoje!', streakDesc: 'Completa uma lição para começar 🫡',
    streakActive: '🔥 Série de {n} dias!', streakActiveDesc: 'Isso aí! Não pares agora!',
    dailyGoal: '📅 Meta do Dia — 50 XP (consegues sim!)',
    xpToday: '{n} XP ganhos hoje', xpGoal: 'Meta: 50 XP',
    dailyChallenge: 'Desafio Diário', dailyChallengeDesc: 'Faz para ganhar +10 XP bónus! Não fica parado 😤',
    dailyDone: '✅ Desafio Completo!', dailyDoneDesc: 'Volta amanhã para um novo desafio!',
    leaderboard: 'Classificação', leaderboardDesc: 'Vê como estás nessa semana',
    wordScramble: 'Palavras Baralhadas', wordScrambleDesc: 'Jogo rápido para ganhar XP extra',
    grammarTitle: '📖 Laboratório de Gramática', grammarSub: 'Domina a gramática inglesa — uma regra de cada vez 💪',
    grammarSearch: 'Pesquisar tópicos de gramática...',
    soundsTitle: '🔊 Laboratório de Sons', soundsSub: 'Ouve, sente, fala — domínio da pronúncia 🎤',
    practiceTab: '🗣️ Praticar', pairsTab: '👥 Pares', twistersTab: '🌀 Trava-línguas', difficultTab: '🎯 Sons',
    hearBtn: '🔊 Ouvir', slowBtn: '🐌 Devagar', recordBtn: '🎤 Gravar',
    pairsNote: 'Clica para ouvir a diferença entre sons parecidos! 👂',
    twistersNote: 'Pratica estes todos os dias — a tua fluência vai a disparar! 🚀',
    difficultNote: 'Sons que dificultam os falantes de português moçambicano 🇲🇿 — domina-os!',
    aiName: 'IA Tutora Sebastian', aiSub: 'Pergunta qualquer coisa sobre inglês! Gramática, vocabulário, pronúncia...',
    aiOnline: 'Online agora', clearChat: '🗑️ Limpar conversa',
    chatPlaceholder: 'Pergunta qualquer coisa ao Sebastian...',
    aiMode: 'Modo', aiModeNormal: '💬 Normal', aiModeGrammar: '📝 Correcção', aiModePron: '🎤 Pronúncia',
    logoutBtn: '🚪 Sair', dayStreak: 'Dias Consecutivos', totalXP: 'XP Total',
    correctAnswers: 'Respostas Certas', lessonsDone: 'Lições Concluídas',
    achievements: '🎖️ Conquistas', settings: '⚙️ Configurações',
    darkLight: '🌓 Modo Escuro / Claro', toggle: 'Alternar',
    interfaceLang: '🌐 Língua da Interface', discoMode: '🕺 Modo Discoteca',
    konami: '🎮 Código Konami',
    close: '✕', continue: 'Continuar ›', seeResults: 'Ver Resultados 🏆',
    correct: '✅ Correcto!', incorrect: '❌ Incorrecto',
    backHome: '🏠 Início', tryAgain: '🔄 Tentar Outra Vez',
    gameTitle: '🔤 Palavras Baralhadas', submitBtn: '🎯 Submeter!',
    surrenderBtn: '💀 Desistir', skipBtn: 'Saltar esta (cobarde 😤)',
    toastDisco: '🕺 MODO DISCOTECA! 🎉', toastDiscoOff: 'Discoteca desligada. Volta ao estudo 📚',
    toastLight: '☀️ Modo claro!', toastDark: '🌙 Modo escuro!',
    toastHeart: '❤️ Coração regenerado!', toastAllDone: '🎓 Todas as lições grátis concluídas! Eras um lenda!',
    toastGameOver: '🎮 Jogo terminado! Pontuação: {n} · +{n} XP!',
    toastKonami: '🎮 CÓDIGO KONAMI! +100 XP!! 🎉',
    premiumTitle: 'Vai Premium!', premiumSub: 'Desbloqueia tudo e torna-te uma lenda do inglês.',
    premiumFeat1: 'Todas as unidades — Phrasal Verbs, Expressões, Avançado',
    premiumFeat2: 'Corações infinitos — falha quantas vezes precisares',
    premiumFeat3: 'Sessões ilimitadas com a IA Tutora',
    premiumFeat4: 'Distintivos exclusivos para mostrar na classificação',
    premiumBtn: '💳 Actualizar — $4.99/mês', premiumSkip: 'Talvez quando me pagarem 💸',
    aboutTitle: 'Sobre o Sebastian', aboutRole: 'Professor de Inglês · Tradutor · Intérprete',
    aboutLocation: '📍 Maputo / Matola, Moçambique 🇲🇿',
    aboutBio: 'Estudante finalista de Tradução e Interpretação na Universidade Eduardo Mondlane, educador apaixonado e professor certificado de inglês com mais de 4 anos de experiência a ajudar estudantes moçambicanos a atingir o seu potencial.',
    aboutStats1: 'Anos de Ensino', aboutStats2: 'Estudantes', aboutStats3: 'Línguas', aboutStats4: 'Lições Criadas',
    aboutEducation: '🎓 Formação', aboutExperience: '💼 Experiência', aboutSkills: '⚡ Competências',
    aboutContact: '📬 Contacto', aboutDownloadCV: '📄 Descarregar CV',
    certifications: '🏅 Certificações',
    levelUp: 'SUBIU DE NÍVEL!!! 🎉', levelUpText: 'Chegaste ao Nível {n}!', letsGo: 'VAMOS A ISSO! 🚀',
    searchPlaceholder: 'Pesquisar lições, gramática, sons...',
    searchEmpty: 'Começa a escrever para pesquisar... 🔎', searchNone: 'Nada encontrado. Tenta palavras diferentes 🤔',
    loadMsg0: 'A aquecer as células cerebrais... 🧠',
    loadMsg1: 'A carregar vocabulário... 📚',
    loadMsg2: 'A calibrar os motores de gramática... 📖',
    loadMsg3: 'A afinar a IA de pronúncia... 🎤',
    loadMsg4: 'A preparar as tuas lições... 🎯',
    loadMsg5: 'Quase lá... ✨',
    lbTitle: '🏆 Melhores Estudantes',
    free: '✓ Grátis', premium: '👑 Premium',
    noHearts: '❤️ Sem corações! Espera 5 min...', alreadyDone: '✅ Já concluído hoje! Volta amanhã.',
    paymentSoon: '🚧 Pagamento em breve — aguarda!',
  },
  // ── British English (en-gb) — same as en with minor differences ──
  'en-gb': {
    appTagline: '🔥 The English app that actually has a personality',
    loginTab: '👋 Log In', signupTab: '✨ Sign Up',
    userPlaceholder: '👤 Username', passPlaceholder: '🔒 Password',
    namePlaceholder: '😎 Your name', newUserPlaceholder: '🆔 Choose a username',
    newPassPlaceholder: '🔑 Password (min 8 chars)',
    loginBtn: "🚀 Let's Go!", signupBtn: '🎉 Create Account!',
    loginErr: '❌ Wrong credentials, mate.', regErr: 'Please fill everything in correctly!',
    userTaken: 'Username taken! Try another one.',
    weakPass: '🔒 Password needs 8+ chars, uppercase, lowercase & a number.',
    passStrWeak: 'Weak', passStrFair: 'Fair', passStrStrong: 'Strong',
    googleBtn: '🔐 Continue with Google', authOr: 'or',
    googleSigningIn: 'Opening Google sign-in…', googleError: 'Google sign-in failed. Try again.',
    googleNotConfigured: 'Google login is not configured yet. Add Supabase keys in supabase-config.js.',
    googlePopupBlocked: 'Pop-up blocked. Allow pop-ups for this site, then try again.',
    search: 'Search', toggleTheme: 'Toggle theme',
    navHome: 'Home', navGrammar: 'Grammar', navSounds: 'Sounds',
    navAI: 'AI Tutor', navProfile: 'Profile', navAbout: 'About',
    homeHeroEyebrow: 'Your learning hub',
    homeHeroGreet: 'Hey,',
    homeHeroSub: 'Level up your English with lessons, games, and your AI tutor — all in one place.',
    homeHeroLevel: 'Level', homeHeroStreak: 'Day streak', homeHeroXP: 'Total XP',
    homeHeroCtaLearn: '▶ Continue learning',
    homeHeroCtaChallenge: '🎲 Daily challenge',
    homeHeroCtaAI: '🤖 Ask AI Tutor',
    dashTitle: 'Your progress', dashSubtitle: 'XP, streaks, lessons & quizzes at a glance',
    dashXP: 'Total XP', dashStreak: 'Day streak', dashLessons: 'Lessons done',
    dashQuizzes: 'Quiz statistics', dashQuizTaken: 'Quizzes taken',
    dashAvgAccuracy: 'Avg accuracy', dashBestScore: 'Best score', dashPerfects: 'Perfect runs',
    dashLevelProgress: 'Level progress', dashDailyProgress: 'Daily goal',
    dashCourseProgress: 'Course progress', dashOf: '{done} of {total}', dashToNext: '{n} XP to Level {lvl}',
    streakTitle: 'Start your streak today!', streakDesc: 'Complete a lesson to begin 🫡',
    streakActive: '🔥 {n}-day streak!', streakActiveDesc: 'Brilliant! Keep it going!',
    dailyGoal: '📅 Daily Goal — 50 XP (you\'ve got this)',
    xpToday: '{n} XP earned today', xpGoal: '50 XP goal',
    dailyChallenge: 'Daily Challenge', dailyChallengeDesc: "Complete for +10 bonus XP! Don't be lazy 😤",
    dailyDone: '✅ Challenge Complete!', dailyDoneDesc: 'Come back tomorrow for a new one!',
    leaderboard: 'Leaderboard', leaderboardDesc: 'See how you rank this week',
    wordScramble: 'Word Scramble', wordScrambleDesc: 'Quick game to earn extra XP',
    grammarTitle: '📖 Grammar Lab', grammarSub: 'Master English grammar — one rule at a time 💪',
    grammarSearch: 'Search grammar topics...',
    soundsTitle: '🔊 Sound Lab', soundsSub: 'Hear it, feel it, speak it — pronunciation mastery 🎤',
    practiceTab: '🗣️ Practice', pairsTab: '👥 Pairs', twistersTab: '🌀 Twisters', difficultTab: '🎯 Sounds',
    hearBtn: '🔊 Hear it', slowBtn: '🐌 Slow', recordBtn: '🎤 Record',
    pairsNote: 'Click to hear the difference between confusable sounds! 👂',
    twistersNote: 'Practice these daily — your fluency will skyrocket! 🚀',
    difficultNote: 'Sounds that trip up Portuguese speakers 🇲🇿 — master these!',
    aiName: 'Sebastian AI Tutor', aiSub: 'Ask me anything about English! Grammar, vocabulary, pronunciation...',
    aiOnline: 'Online now', clearChat: '🗑️ Clear chat', chatPlaceholder: 'Ask Sebastian anything...',
    aiMode: 'Mode', aiModeNormal: '💬 Normal', aiModeGrammar: '📝 Grammar Check', aiModePron: '🎤 Pronunciation',
    logoutBtn: '🚪 Log Out', dayStreak: 'Day Streak', totalXP: 'Total XP',
    correctAnswers: 'Correct Answers', lessonsDone: 'Lessons Done',
    achievements: '🎖️ Achievements', settings: '⚙️ Settings',
    darkLight: '🌓 Dark / Light Mode', toggle: 'Toggle',
    interfaceLang: '🌐 Interface Language', discoMode: '🕺 Disco Mode', konami: '🎮 Konami Code',
    close: '✕', continue: 'Continue ›', seeResults: 'See Results 🏆',
    correct: '✅ Correct!', incorrect: '❌ Incorrect',
    backHome: '🏠 Back Home', tryAgain: '🔄 Try Again',
    gameTitle: '🔤 Word Scramble Madness', submitBtn: '🎯 Submit!',
    surrenderBtn: '💀 Surrender', skipBtn: 'Skip this one (coward 😤)',
    toastDisco: '🕺 DISCO MODE! 🎉', toastDiscoOff: 'Disco off. Back to learning 📚',
    toastLight: '☀️ Light mode!', toastDark: '🌙 Dark mode!',
    toastHeart: '❤️ Heart regenerated!', toastAllDone: '🎓 All free lessons completed! You\'re a legend!',
    toastGameOver: '🎮 Game over! Score: {n} · +{n} XP!',
    toastKonami: '🎮 KONAMI CODE! +100 XP!! 🎉',
    premiumTitle: 'Go Premium!', premiumSub: 'Unlock everything and become an English legend.',
    premiumFeat1: 'All units — Phrasal Verbs, Idioms, Advanced',
    premiumFeat2: 'Infinite hearts — fail as many times as you need',
    premiumFeat3: 'Unlimited AI Tutor sessions',
    premiumFeat4: 'Exclusive badges to flex on the leaderboard',
    premiumBtn: '💳 Upgrade — $4.99/month', premiumSkip: 'Maybe when I get paid 💸',
    aboutTitle: 'About Sebastian', aboutRole: 'English Teacher · Translator · Interpreter',
    aboutLocation: '📍 Maputo / Matola, Mozambique',
    aboutBio: 'Final-year Translation & Interpretation student at Universidade Eduardo Mondlane, passionate educator, and certified English teacher with 4+ years of experience helping students unlock their potential.',
    aboutStats1: 'Years Teaching', aboutStats2: 'Students Taught', aboutStats3: 'Languages', aboutStats4: 'Lessons Created',
    aboutEducation: '🎓 Education', aboutExperience: '💼 Experience', aboutSkills: '⚡ Skills',
    aboutContact: '📬 Get in Touch', aboutDownloadCV: '📄 Download CV',
    certifications: '🏅 Certifications',
    levelUp: 'LEVEL UP!!! 🎉', levelUpText: 'You reached Level {n}!', letsGo: "LET'S GOOOO! 🚀",
    searchPlaceholder: 'Search lessons, grammar, sounds...',
    searchEmpty: 'Start typing to search... 🔎', searchNone: 'Nothing found. Try different words 🤔',
    loadMsg0: 'Warming up your brain cells... 🧠',
    loadMsg1: 'Loading vocabulary banks... 📚',
    loadMsg2: 'Calibrating grammar engines... 📖',
    loadMsg3: 'Tuning pronunciation AI... 🎤',
    loadMsg4: 'Preparing your lessons... 🎯',
    loadMsg5: 'Almost there... ✨',
    lbTitle: '🏆 Top Learners',
    free: '✓ Free', premium: '👑 Premium',
    noHearts: '❤️ No hearts left! Wait 5 min...', alreadyDone: '✅ Already done today! Come back tomorrow.',
    paymentSoon: '🚧 Payment coming soon — stay tuned!',
  },
  // ── European Portuguese (pt-pt) ──
  'pt-pt': {
    appTagline: '🔥 A app de inglês que tem mesmo personalidade',
    loginTab: '👋 Entrar', signupTab: '✨ Registar',
    userPlaceholder: '👤 Nome de utilizador', passPlaceholder: '🔒 Palavra-passe',
    namePlaceholder: '😎 O teu nome', newUserPlaceholder: '🆔 Escolhe um utilizador',
    newPassPlaceholder: '🔑 Palavra-passe (mín. 8 caracteres)',
    loginBtn: '🚀 Vamos lá!', signupBtn: '🎉 Criar Conta!',
    loginErr: '❌ Credenciais erradas, pá!', regErr: 'Preenche tudo correctamente, se faz favor!',
    userTaken: 'Utilizador já existe! Tenta outro.',
    weakPass: '🔒 A palavra-passe precisa de 8+ caracteres, maiúscula, minúscula e número.',
    passStrWeak: 'Fraca', passStrFair: 'Razoável', passStrStrong: 'Forte',
    googleBtn: '🔐 Continuar com Google', authOr: 'ou',
    googleSigningIn: 'A abrir o Google…', googleError: 'Falha no login do Google. Tenta outra vez.',
    googleNotConfigured: 'Login Google não configurado. Adiciona as chaves em supabase-config.js.',
    googlePopupBlocked: 'Pop-up bloqueado. Permite pop-ups neste site e tenta novamente.',
    search: 'Pesquisar', toggleTheme: 'Mudar tema',
    navHome: 'Início', navGrammar: 'Gramática', navSounds: 'Sons',
    navAI: 'Tutor IA', navProfile: 'Perfil', navAbout: 'Sobre',
    homeHeroEyebrow: 'O teu centro de aprendizagem',
    homeHeroGreet: 'Olá,',
    homeHeroSub: 'Melhora o teu inglês com lições, jogos e o tutor IA — tudo num só lugar.',
    homeHeroLevel: 'Nível', homeHeroStreak: 'Dias seguidos', homeHeroXP: 'XP total',
    homeHeroCtaLearn: '▶ Continuar a aprender',
    homeHeroCtaChallenge: '🎲 Desafio diário',
    homeHeroCtaAI: '🤖 Perguntar ao Tutor IA',
    dashTitle: 'O teu progresso', dashSubtitle: 'XP, séries, lições e quizzes de uma vez',
    dashXP: 'XP total', dashStreak: 'Dias seguidos', dashLessons: 'Lições concluídas',
    dashQuizzes: 'Estatísticas de quiz', dashQuizTaken: 'Quizzes realizados',
    dashAvgAccuracy: 'Precisão média', dashBestScore: 'Melhor resultado', dashPerfects: 'Quizzes perfeitos',
    dashLevelProgress: 'Progresso de nível', dashDailyProgress: 'Meta diária',
    dashCourseProgress: 'Progresso do curso', dashOf: '{done} de {total}', dashToNext: '{n} XP para o Nível {lvl}',
    streakTitle: 'Começa a tua série hoje!', streakDesc: 'Completa uma lição para começar 🫡',
    streakActive: '🔥 Série de {n} dias!', streakActiveDesc: 'Óptimo! Continua assim!',
    dailyGoal: '📅 Meta Diária — 50 XP (tu consegues)',
    xpToday: '{n} XP ganhos hoje', xpGoal: 'Meta: 50 XP',
    dailyChallenge: 'Desafio Diário', dailyChallengeDesc: 'Completa para +10 XP bónus! Não sejas preguiçoso 😤',
    dailyDone: '✅ Desafio Completo!', dailyDoneDesc: 'Volta amanhã para um novo desafio!',
    leaderboard: 'Classificação', leaderboardDesc: 'Vê como estás classificado esta semana',
    wordScramble: 'Palavras Baralhadas', wordScrambleDesc: 'Jogo rápido para ganhar XP extra',
    grammarTitle: '📖 Laboratório de Gramática', grammarSub: 'Domina a gramática inglesa — uma regra de cada vez 💪',
    grammarSearch: 'Pesquisar tópicos de gramática...',
    soundsTitle: '🔊 Laboratório de Sons', soundsSub: 'Ouve, sente, fala — domínio da pronúncia 🎤',
    practiceTab: '🗣️ Praticar', pairsTab: '👥 Pares', twistersTab: '🌀 Trava-línguas', difficultTab: '🎯 Sons',
    hearBtn: '🔊 Ouvir', slowBtn: '🐌 Devagar', recordBtn: '🎤 Gravar',
    pairsNote: 'Clica para ouvires a diferença entre sons confundíveis! 👂',
    twistersNote: 'Pratica estes diariamente — a tua fluência vai disparar! 🚀',
    difficultNote: 'Sons que dificultam os falantes de português 🇵🇹 — domina-os!',
    aiName: 'Tutor IA Sebastian', aiSub: 'Pergunta-me qualquer coisa sobre inglês! Gramática, vocabulário, pronúncia...',
    aiOnline: 'Online agora', clearChat: '🗑️ Limpar conversa', chatPlaceholder: 'Pergunta qualquer coisa ao Sebastian...',
    aiMode: 'Modo', aiModeNormal: '💬 Normal', aiModeGrammar: '📝 Correcção', aiModePron: '🎤 Pronúncia',
    logoutBtn: '🚪 Terminar sessão', dayStreak: 'Dias Consecutivos', totalXP: 'XP Total',
    correctAnswers: 'Respostas Correctas', lessonsDone: 'Lições Concluídas',
    achievements: '🎖️ Conquistas', settings: '⚙️ Definições',
    darkLight: '🌓 Modo Escuro / Claro', toggle: 'Alternar',
    interfaceLang: '🌐 Idioma da Interface', discoMode: '🕺 Modo Discoteca', konami: '🎮 Código Konami',
    close: '✕', continue: 'Continuar ›', seeResults: 'Ver Resultados 🏆',
    correct: '✅ Correcto!', incorrect: '❌ Incorrecto',
    backHome: '🏠 Início', tryAgain: '🔄 Tentar Novamente',
    gameTitle: '🔤 Palavras Baralhadas', submitBtn: '🎯 Submeter!',
    surrenderBtn: '💀 Desistir', skipBtn: 'Saltar esta (cobarde 😤)',
    toastDisco: '🕺 MODO DISCOTECA! 🎉', toastDiscoOff: 'Discoteca desligada. Volta ao estudo 📚',
    toastLight: '☀️ Modo claro!', toastDark: '🌙 Modo escuro!',
    toastHeart: '❤️ Coração regenerado!', toastAllDone: '🎓 Todas as lições gratuitas concluídas! És uma lenda!',
    toastGameOver: '🎮 Jogo terminado! Pontuação: {n} · +{n} XP!',
    toastKonami: '🎮 CÓDIGO KONAMI! +100 XP!! 🎉',
    premiumTitle: 'Torna-te Premium!', premiumSub: 'Desbloqueia tudo e torna-te uma lenda do inglês.',
    premiumFeat1: 'Todas as unidades — Phrasal Verbs, Expressões, Avançado',
    premiumFeat2: 'Corações infinitos — falha quantas vezes precisares',
    premiumFeat3: 'Sessões ilimitadas com o Tutor IA',
    premiumFeat4: 'Distintivos exclusivos para mostrar na classificação',
    premiumBtn: '💳 Actualizar — $4.99/mês', premiumSkip: 'Talvez quando me pagarem 💸',
    aboutTitle: 'Sobre o Sebastian', aboutRole: 'Professor de Inglês · Tradutor · Intérprete',
    aboutLocation: '📍 Maputo / Matola, Moçambique',
    aboutBio: 'Estudante finalista de Tradução e Interpretação na Universidade Eduardo Mondlane, educador apaixonado e professor certificado de inglês com mais de 4 anos de experiência a ajudar estudantes a atingir o seu potencial.',
    aboutStats1: 'Anos de Ensino', aboutStats2: 'Estudantes', aboutStats3: 'Línguas', aboutStats4: 'Lições Criadas',
    aboutEducation: '🎓 Formação', aboutExperience: '💼 Experiência', aboutSkills: '⚡ Competências',
    aboutContact: '📬 Contacto', aboutDownloadCV: '📄 Descarregar CV',
    certifications: '🏅 Certificações',
    levelUp: 'SUBIU DE NÍVEL!!! 🎉', levelUpText: 'Chegaste ao Nível {n}!', letsGo: 'VAMOS LÁ! 🚀',
    searchPlaceholder: 'Pesquisar lições, gramática, sons...',
    searchEmpty: 'Começa a escrever para pesquisar... 🔎', searchNone: 'Nada encontrado. Tenta palavras diferentes 🤔',
    loadMsg0: 'A aquecer as células cerebrais... 🧠',
    loadMsg1: 'A carregar vocabulário... 📚',
    loadMsg2: 'A calibrar os motores de gramática... 📖',
    loadMsg3: 'A afinar o tutor IA de pronúncia... 🎤',
    loadMsg4: 'A preparar as tuas lições... 🎯',
    loadMsg5: 'Quase lá... ✨',
    lbTitle: '🏆 Melhores Estudantes',
    free: '✓ Grátis', premium: '👑 Premium',
    noHearts: '❤️ Sem corações! Espera 5 min...', alreadyDone: '✅ Já concluído hoje! Volta amanhã.',
    paymentSoon: '🚧 Pagamento em breve — mantém-te atento!',
  }
};

// ─── LEVELS ──────────────────────────────────────────────
const LEVELS = [
  {level:1,title:'Beginner',titlePt:'Iniciante',prev:0,next:100},
  {level:2,title:'Elementary',titlePt:'Elementar',prev:100,next:250},
  {level:3,title:'Pre-Intermediate',titlePt:'Pré-Intermédio',prev:250,next:500},
  {level:4,title:'Intermediate',titlePt:'Intermédio',prev:500,next:900},
  {level:5,title:'Upper-Intermediate',titlePt:'Intermédio Superior',prev:900,next:1400},
  {level:6,title:'Advanced',titlePt:'Avançado',prev:1400,next:2000},
  {level:7,title:'Fluent',titlePt:'Fluente',prev:2000,next:9999},
];

// ─── ACHIEVEMENTS ────────────────────────────────────────
const ACHS = [
  {id:'first',icon:'🌱',name:'First Step',namePt:'Primeiro Passo',c:u=>u.done.length>=1},
  {id:'5less',icon:'📚',name:'Book Worm',namePt:'Rato de Biblioteca',c:u=>u.done.length>=5},
  {id:'10less',icon:'🎓',name:'Scholar',namePt:'Académico',c:u=>u.done.length>=10},
  {id:'allless',icon:'🏆',name:'Completionist',namePt:'Perfeccionista',c:u=>u.done.length>=18},
  {id:'str3',icon:'🔥',name:'On Fire',namePt:'Em Chamas',c:u=>u.streak>=3},
  {id:'str7',icon:'💥',name:'Week Warrior',namePt:'Guerreiro Semanal',c:u=>u.streak>=7},
  {id:'str30',icon:'🌩️',name:'Monthly Legend',namePt:'Lenda Mensal',c:u=>u.streak>=30},
  {id:'xp100',icon:'⚡',name:'XP Hunter',namePt:'Caçador de XP',c:u=>u.xp>=100},
  {id:'xp500',icon:'💎',name:'XP Legend',namePt:'Lenda XP',c:u=>u.xp>=500},
  {id:'xp1000',icon:'👑',name:'XP Master',namePt:'Mestre XP',c:u=>u.xp>=1000},
  {id:'perfect',icon:'✨',name:'Perfectionist',namePt:'Perfeccionista',c:u=>u.hadPerfect},
  {id:'combo5',icon:'💫',name:'Combo Master',namePt:'Mestre do Combo',c:u=>(u.maxCombo||0)>=5},
  {id:'ai1',icon:'🤖',name:'AI Friend',namePt:'Amigo da IA',c:u=>(u.aiChats||0)>=1},
  {id:'ai10',icon:'🤖',name:'AI Addict',namePt:'Viciado em IA',c:u=>(u.aiChats||0)>=10},
  {id:'game100',icon:'🎮',name:'Scramble Pro',namePt:'Pro do Baralho',c:u=>(u.scrambleScore||0)>=100},
  {id:'pron5',icon:'🎤',name:'Speaker',namePt:'Orador',c:u=>(u.pronP||0)>=5},  // pronP is incremented in ui.js — do NOT remove that logic
  {id:'gram5',icon:'📖',name:'Grammar Nerd',namePt:'Nerd da Gramática',c:u=>(u.gramR||0)>=5},  // gramR is incremented in ui.js — do NOT remove that logic
  {id:'allach',icon:'🌟',name:'All Rounder',namePt:'Completo',c:u=>u.achs.length>=10},
];

// ─── MASCOT MESSAGES ─────────────────────────────────────
const MASCOT_MSGS = {
  en: [
    '🎓 Sebastian says: Keep going! Every lesson = brain gains!',
    '💪 You\'re doing great! Don\'t stop now!',
    '🔥 That streak isn\'t gonna keep itself!',
    '🤖 Pro tip: Use the AI Tutor when you\'re confused!',
    '🔊 Try the Sound Lab — your accent will thank you!',
    '📖 The Grammar Lab has everything you need!',
    '😎 Native speakers make mistakes too. They just keep talking!',
    '🌍 English opens doors. Keep pushing!',
    '🎯 30 minutes a day = fluent in 2 years. You got this!',
    '🏆 Top of the leaderboard? That could be YOU!',
  ],
  pt: [
    '🎓 Sebastian diz: Continua! Cada lição = progresso!',
    '💪 Estás a sair-te bem! Não pares agora!',
    '🔥 Essa série não se mantém sozinha!',
    '🤖 Dica: Usa a IA Tutora quando tiveres dúvidas!',
    '🔊 Experimenta o Laboratório de Sons — a tua pronúncia vai agradecer!',
    '📖 O Laboratório de Gramática tem tudo que precisas!',
    '😎 Falantes nativos também erram. Eles apenas continuam!',
    '🌍 O inglês abre portas. Continua!',
    '🎯 30 minutos por dia = fluente em 2 anos. Consegues!',
    '🏆 Topo da classificação? Podes ser TU!',
  ]
};

// ─── RANDOM TIPS ─────────────────────────────────────────
const TIPS = {
  en: [
    '💡 Complete daily challenges for bonus XP!',
    '🔥 Keep your streak alive — come back tomorrow!',
    '🎮 Try the Word Scramble game for extra XP!',
    '💪 Consistency beats talent — keep going!',
    '🤖 Ask the AI Tutor anything — it\'s free!',
    '🔊 Practice pronunciation every day — even 5 minutes helps!',
  ],
  pt: [
    '💡 Completa os desafios diários para XP bónus!',
    '🔥 Mantém a tua série — volta amanhã!',
    '🎮 Experimenta as Palavras Baralhadas para XP extra!',
    '💪 A consistência supera o talento — continua!',
    '🤖 Pergunta qualquer coisa à IA Tutora — é grátis!',
    '🔊 Pratica pronúncia todos os dias — até 5 minutos ajuda!',
  ]
};

// ─── QUIZ MESSAGES ───────────────────────────────────────
const QUIZ_MSGS = {
  en: {
    correct: ['Nailed it! 🎯','Perfect! ✨','Boom! 💥','Easy money 💰','Too smart! 🧠','Keep it up! 🔥','You\'re on fire! 🚀','Excellent! 💪'],
    wrong: ['Oops... not quite 😬','Almost! Keep going 💪','Brain fart? It happens 😅','Come on, you\'re better than this!','Review and try again! 📚'],
    results: {
      perfect: ['PERFECT!', 'Absolutely CRUSHED it! 🔥'],
      great: ['Great job!', 'Solid work! Almost perfect!'],
      ok: ['Not bad!', 'Good effort! Review the mistakes.'],
      tryAgain: ['Keep trying!', 'Review and try again — you got this!'],
    }
  },
  pt: {
    correct: ['Excelente! 🎯','Perfeito! ✨','Boom! 💥','Fácil! 💰','Demasiado inteligente! 🧠','Continua! 🔥','Estás em chamas! 🚀','Fantástico! 💪'],
    wrong: ['Oops... não foi bem 😬','Quase! Continua 💪','Lapso mental? Acontece 😅','Vá, és melhor que isso!','Revê e tenta novamente! 📚'],
    results: {
      perfect: ['PERFEITO!', 'Absolutamente ARRASOU! 🔥'],
      great: ['Muito bem!', 'Trabalho sólido! Quase perfeito!'],
      ok: ['Não foi mau!', 'Bom esforço! Revê os erros.'],
      tryAgain: ['Continua a tentar!', 'Revê e tenta novamente — consegues!'],
    }
  }
};

// ─── CURRICULUM DATA ─────────────────────────────────────

// ─── UNITS (30+ lessons, A0→Advanced) ────────────────────
const UNITS = [
  // ══════════════════════════════════════════════════════
  //  UNIT 0 — BEGINNER ZERO (A0) — absolute beginners
  // ══════════════════════════════════════════════════════
  {
    id:'u0', title:'Beginner Zero', titlePt:'Nível Zero',
    desc:'Start here if you know ZERO English 🌱',
    descPt:'Começa aqui se não sabes nada de inglês 🌱',
    color:'#00bfa5', icon:'🌱', premium:false,
    lessons:[
      {id:'l0a', title:'What is English?', titlePt:'O que é o Inglês?', icon:'🌍', xp:10, qs:[
        {q:'English is a ___.',opts:['language','animal','colour','food'],ans:0,exp:'"English" is a language — a way of communicating!'},
        {q:'English is spoken in how many countries?',opts:['2','10','50','over 50'],ans:3,exp:'English is spoken in over 50 countries! It is truly a global language.'},
        {q:'Which country speaks English as its official language?',opts:['Brazil','Portugal','USA','Mozambique'],ans:2,exp:'The USA (United States of America) has English as its main language.'},
        {q:'Why learn English?',opts:['To forget Portuguese','To travel, work and communicate globally','It\'s easy','To watch TV only'],ans:1,exp:'English opens doors: travel, jobs, university, internet and more!'},
        {q:'The English alphabet has ___ letters.',opts:['20','24','26','30'],ans:2,exp:'The English alphabet has 26 letters: A to Z!'},
      ]},
      {id:'l0b', title:'The Alphabet A-Z', titlePt:'O Alfabeto A-Z', icon:'🔤', xp:15, qs:[
        {q:'Which comes FIRST in the alphabet?',opts:['B','A','C','D'],ans:1,exp:'A is the first letter: A, B, C, D, E, F, G...'},
        {q:'How many vowels does English have?',opts:['3','5','7','10'],ans:1,exp:'English has 5 vowels: A, E, I, O, U'},
        {q:'Which letter is a VOWEL?',opts:['B','C','E','T'],ans:2,exp:'E is a vowel. Vowels are: A, E, I, O, U'},
        {q:'What comes after M in the alphabet?',opts:['L','K','N','P'],ans:2,exp:'...K, L, M, N, O, P... N comes after M!'},
        {q:'Which word starts with the letter "H"?',opts:['Apple','Elephant','Hello','Dog'],ans:2,exp:'"Hello" starts with H. Hello! 👋'},
      ]},
      {id:'l0c', title:'Greetings & Goodbyes', titlePt:'Saudações e Despedidas', icon:'👋', xp:15, qs:[
        {q:'How do you say "Olá" in English?',opts:['Goodbye','Thank you','Hello','Please'],ans:2,exp:'"Hello" = Olá. You can also say "Hi!" (informal)'},
        {q:'"Good morning" is used:',opts:['At night','In the morning','At lunchtime','Any time'],ans:1,exp:'"Good morning" = Bom dia. Used in the morning!'},
        {q:'How do you say "Até logo" in English?',opts:['Hello','How are you?','Goodbye','Please'],ans:2,exp:'"Goodbye" = Até logo / Adeus. Also "Bye!" (informal)'},
        {q:'"How are you?" is a ___.',opts:['command','greeting','number','colour'],ans:1,exp:'"How are you?" = Como estás? It\'s a greeting!'},
        {q:'The correct response to "How are you?" is:',opts:['My name is Ana','I am fine, thank you','Goodbye','Yes, please'],ans:1,exp:'"I am fine, thank you" = Estou bem, obrigado/a. The perfect reply!'},
      ]},
      {id:'l0d', title:'Introducing Yourself', titlePt:'Apresentar-se', icon:'🙋', xp:20, qs:[
        {q:'"My name is ___." This sentence introduces:',opts:['your age','your name','your job','your city'],ans:1,exp:'"My name is..." = O meu nome é... Use it to introduce yourself!'},
        {q:'Complete: "I ___ from Mozambique."',opts:['is','am','are','be'],ans:1,exp:'"I am from..." Use "am" with "I". I am from Mozambique!'},
        {q:'"I am 25 years ___."',opts:['old','age','young','year'],ans:0,exp:'"I am 25 years old." = Tenho 25 anos. Always use "old"!'},
        {q:'Which sentence correctly introduces someone?',opts:['My name are Ana.','My name am Ana.','My name is Ana.','Me name is Ana.'],ans:2,exp:'"My name IS Ana." — use "is" for names!'},
        {q:'"Nice to meet you!" means:',opts:['Goodbye!','I don\'t know you.','Happy to meet you!','See you later!'],ans:2,exp:'"Nice to meet you!" = Muito prazer! Say this when meeting someone new.'},
      ]},
      {id:'l0e', title:'Numbers 1-20', titlePt:'Números 1-20', icon:'🔢', xp:15, qs:[
        {q:'What is "five" in numbers?',opts:['3','4','5','6'],ans:2,exp:'five = 5. One, two, three, four, five!'},
        {q:'How do you write 10 in words?',opts:['twelve','eight','ten','eleven'],ans:2,exp:'10 = ten. Count: one, two, three... ten!'},
        {q:'"Fifteen" is:',opts:['13','14','15','16'],ans:2,exp:'fifteen = 15. Five + Ten = Fifteen!'},
        {q:'What comes after "nineteen"?',opts:['eighteen','twenty','seventeen','thirteen'],ans:1,exp:'After nineteen (19) comes twenty (20)!'},
        {q:'Which number is "twelve"?',opts:['10','11','12','13'],ans:2,exp:'twelve = 12. A dozen = twelve!'},
      ]},
      {id:'l0f', title:'Colours', titlePt:'Cores', icon:'🎨', xp:15, qs:[
        {q:'What colour is the sky?',opts:['green','red','blue','yellow'],ans:2,exp:'The sky is BLUE! 🔵 "The sky is blue."'},
        {q:'"Red" in Portuguese is:',opts:['Azul','Verde','Vermelho','Amarelo'],ans:2,exp:'red = vermelho. "The rose is red." 🌹'},
        {q:'What colour is grass?',opts:['blue','green','orange','purple'],ans:1,exp:'Grass is GREEN! 🌿 "The grass is green."'},
        {q:'"Yellow" is the colour of:',opts:['the sea','the sun','the night','the soil'],ans:1,exp:'The sun is YELLOW! ☀️ "The sun is yellow."'},
        {q:'Which colour is NOT in the rainbow?',opts:['red','brown','blue','green'],ans:1,exp:'Brown is NOT in the rainbow. Rainbow = red, orange, yellow, green, blue, indigo, violet.'},
      ]},
      {id:'l0g', title:'Family Members', titlePt:'Membros da Família', icon:'👨‍👩‍👧‍👦', xp:20, qs:[
        {q:'"Mother" means:',opts:['irmã','mãe','avó','tia'],ans:1,exp:'mother = mãe. "My mother is kind."'},
        {q:'What is "father" in Portuguese?',opts:['irmão','tio','pai','avô'],ans:2,exp:'father = pai. "My father is strong."'},
        {q:'"Brother" and "sister" are your:',opts:['parents','grandparents','siblings','children'],ans:2,exp:'Brother and sister = siblings (irmãos). Part of your immediate family!'},
        {q:'What do you call your mother\'s mother?',opts:['aunt','sister','grandmother','cousin'],ans:2,exp:'Your mother\'s mother = grandmother (avó)!'},
        {q:'"I have two ___." (brother + sister)',opts:['parents','siblings','cousins','grandparents'],ans:1,exp:'Brother + sister = siblings. "I have two siblings."'},
      ]},
      {id:'l0h', title:'My First Conversation', titlePt:'A Minha Primeira Conversa', icon:'💬', xp:25, qs:[
        {q:'Put in order: "___ am I. Sebastian name My."',opts:['My name I am Sebastian.','My name is Sebastian.','I Sebastian name am.','Sebastian my name.'],ans:1,exp:'"My name is Sebastian." — Subject + Verb + Object!'},
        {q:'A: "Hello!" B: "___"',opts:['Goodbye!','Hello! How are you?','My name is Ana.','I am fine.'],ans:1,exp:'"Hello! How are you?" — Reply to a greeting with a greeting!'},
        {q:'A: "Where are you from?" B: "___"',opts:['I am 20 years old.','I am fine.','I am from Mozambique.','My name is Tom.'],ans:2,exp:'"I am from Mozambique." — Answer "Where from?" with "I am from..."'},
        {q:'How do you say "thank you" in English?',opts:['Please','Sorry','Thank you','Excuse me'],ans:2,exp:'"Thank you" = Obrigado/a. Always be polite!'},
        {q:'To end a conversation politely you say:',opts:['Hello!','How are you?','Nice to meet you!','Goodbye! Have a nice day!'],ans:3,exp:'"Goodbye! Have a nice day!" = Até logo! Tenha um bom dia! 👋'},
      ]},
    ]
  },

  // ══════════════════════════════════════════════════════
  //  UNIT 1 — PRESENT TENSES (A1-A2)
  // ══════════════════════════════════════════════════════
  {
    id:'u1', title:'Present Tenses', titlePt:'Tempos Presentes',
    desc:'Master the most-used tenses in English 🕐',
    descPt:'Domina os tempos presentes mais usados 🕐',
    color:'#2979ff', icon:'🕐', premium:false,
    lessons:[
      {id:'l1', title:'Verb To Be', titlePt:'Verbo To Be', icon:'🔵', xp:20, qs:[
        {q:'"She ___ a teacher."',opts:['am','is','are','be'],ans:1,exp:'"She IS a teacher." — He/She/It = IS'},
        {q:'"We ___ from Mozambique."',opts:['am','is','are','be'],ans:2,exp:'"We ARE from Mozambique." — We/You/They = ARE'},
        {q:'Negative of "I am happy":',opts:['I is not happy.','I am not happy.','I are not happy.','I be not happy.'],ans:1,exp:'"I am not happy." — I + am. Negative = am not / I\'m not'},
        {q:'"___ you a student?"',opts:['Am','Is','Are','Be'],ans:2,exp:'"ARE you a student?" — You = ARE'},
        {q:'"They ___ not here."',opts:['am','is','are','was'],ans:2,exp:'"They ARE not here." — They + are. Negative = are not / aren\'t'},
      ]},
      {id:'l2', title:'Subject Pronouns', titlePt:'Pronomes Pessoais', icon:'👤', xp:15, qs:[
        {q:'What pronoun replaces "Ana"?',opts:['He','She','It','They'],ans:1,exp:'"Ana" is a woman → SHE. "Ana is kind." = "She is kind."'},
        {q:'"The dog is hungry." Replace "the dog":',opts:['He','She','It','They'],ans:2,exp:'Animals and objects = IT. "The dog is hungry." = "It is hungry."'},
        {q:'"Pedro and I are friends." Replace with one pronoun:',opts:['We','They','He','You'],ans:0,exp:'"Pedro and I" = WE. "We are friends."'},
        {q:'What pronoun replaces "Mr. Silva"?',opts:['She','It','He','They'],ans:2,exp:'"Mr. Silva" is a man → HE. "Mr. Silva works here." = "He works here."'},
        {q:'"Ana and Pedro are students." Replace:',opts:['We','He','She','They'],ans:3,exp:'"Ana and Pedro" = THEY. Two or more people = THEY.'},
      ]},
      {id:'l3', title:'Simple Present', titlePt:'Presente Simples', icon:'⭕', xp:25, qs:[
        {q:'Which is correct?',opts:['She go to school.','She goes to school.','She is go.','She going.'],ans:1,exp:'"She GOES to school." — He/She/It adds -s or -es!'},
        {q:'"He ___ like coffee."',opts:['don\'t','doesn\'t','not','isn\'t'],ans:1,exp:'"He DOESN\'T like coffee." — Negative: doesn\'t + base verb.'},
        {q:'"I ___ English every day."',opts:['studies','studying','study','to study'],ans:2,exp:'"I STUDY English every day." — I/You/We/They: base form, no -s.'},
        {q:'Which word signals Simple Present?',opts:['yesterday','now','always','tomorrow'],ans:2,exp:'"Always", "usually", "often", "every day" = Simple Present signals!'},
        {q:'"___ she live in Maputo?"',opts:['Do','Does','Is','Are'],ans:1,exp:'"DOES she live in Maputo?" — Questions with He/She/It use DOES.'},
      ]},
      {id:'l4', title:'Present Continuous', titlePt:'Presente Contínuo', icon:'🔄', xp:25, qs:[
        {q:'"Look! It ___ (rain)"',opts:['rains','rained','is raining','has rained'],ans:2,exp:'"It IS RAINING." — Present Continuous = am/is/are + verb-ing.'},
        {q:'Which is WRONG?',opts:['I am eating.','She is running.','They are knowing.','We are waiting.'],ans:2,exp:'"Knowing" is wrong! Stative verbs (know, like, want) cannot use -ing.'},
        {q:'"They ___ playing football now."',opts:['is','am','are','be'],ans:2,exp:'"They ARE playing." — They + are + verb-ing.'},
        {q:'What is "write" in Present Continuous?',opts:['writing','writeing','writting','wrotes'],ans:0,exp:'"Writing" — drop the silent "e" before adding -ing: write → writing.'},
        {q:'"She is always ___ her keys." (lose)',opts:['lose','lost','losing','to lose'],ans:2,exp:'"Losing" — continuous = verb-ing. lose → losing!'},
      ]},
      {id:'l5', title:'Present Perfect', titlePt:'Presente Perfeito', icon:'✅', xp:30, qs:[
        {q:'"I ___ never been to Japan."',opts:['have','has','had','am'],ans:0,exp:'"I HAVE never been." — I/You/We/They = HAVE.'},
        {q:'Which uses Present Perfect CORRECTLY?',opts:['She has went to Paris.','She went to Paris yesterday.','She has been to Paris.','She have been to Paris.'],ans:2,exp:'"She HAS BEEN to Paris." — No specific time = Present Perfect!'},
        {q:'"They ___ already finished."',opts:['have','has','had','did'],ans:0,exp:'"They HAVE already finished." — "already" = big Present Perfect clue!'},
        {q:'Which signal word goes with Present Perfect?',opts:['yesterday','last year','in 2010','just'],ans:3,exp:'"Just", "already", "yet", "ever", "never", "since", "for" = Perfect signals!'},
        {q:'"Have you ___ sushi?" (eat)',opts:['eat','ate','eaten','eating'],ans:2,exp:'After have/has = past participle. eat → eaten. Irregular!'},
      ]},
    ]
  },

  // ══════════════════════════════════════════════════════
  //  UNIT 2 — PAST TENSES
  // ══════════════════════════════════════════════════════
  {
    id:'u2', title:'Past Tenses', titlePt:'Tempos Passados',
    desc:'Talk about history & completed actions 📜',
    descPt:'Fala sobre o passado e acções concluídas 📜',
    color:'#ff6d00', icon:'⏮️', premium:false,
    lessons:[
      {id:'l6', title:'Simple Past', titlePt:'Passado Simples', icon:'⏮️', xp:25, qs:[
        {q:'"She ___ a letter yesterday." (write)',opts:['writes','write','wrote','written'],ans:2,exp:'"Write" is irregular: write → WROTE.'},
        {q:'"They ___ not go to school last Monday."',opts:['did','do','does','have'],ans:0,exp:'Negative: DID + not + base verb. "They did not go."'},
        {q:'What is the past of "buy"?',opts:['buyed','boughted','bought','buyt'],ans:2,exp:'"Buy → Bought" — irregular verb!'},
        {q:'Which signals Simple Past?',opts:['just','since','already','three days ago'],ans:3,exp:'"Three days ago", "yesterday", "last week" = Simple Past signals.'},
        {q:'"___ you see the match last night?"',opts:['Did','Do','Does','Have'],ans:0,exp:'Past questions: DID + subject + base verb?'},
      ]},
      {id:'l7', title:'Past Continuous', titlePt:'Passado Contínuo', icon:'⏸️', xp:25, qs:[
        {q:'"While I ___, the phone rang." (sleep)',opts:['sleep','slept','was sleeping','have slept'],ans:2,exp:'Past Continuous = was/were + -ing. Ongoing action interrupted!'},
        {q:'"They ___ football when it started raining."',opts:['played','were playing','have played','play'],ans:1,exp:'"WERE PLAYING" — ongoing action interrupted by rain.'},
        {q:'Choose the CORRECT sentence:',opts:['She was cry.','She was cried.','She were crying.','She was crying.'],ans:3,exp:'"She WAS CRYING." — was/were + -ing.'},
        {q:'"What ___ you doing at 9pm last night?"',opts:['did','were','have','are'],ans:1,exp:'"WERE you doing?" — Past Continuous question.'},
        {q:'Past Continuous describes:',opts:['Past habits','Finished actions','Ongoing past actions','Future plans'],ans:2,exp:'Past Continuous = actions IN PROGRESS at a specific past moment.'},
      ]},
    ]
  },

  // ══════════════════════════════════════════════════════
  //  UNIT 3 — FUTURE
  // ══════════════════════════════════════════════════════
  {
    id:'u3', title:'Future', titlePt:'Futuro',
    desc:"Talk about what's coming! 🔮",
    descPt:'Fala sobre o que está a vir! 🔮',
    color:'#82b1ff', icon:'🚀', premium:false,
    lessons:[
      {id:'l8', title:'Future with Will', titlePt:'Futuro com Will', icon:'🔮', xp:25, qs:[
        {q:'"I think it ___ rain tomorrow."',opts:['is going to','will','rains','rained'],ans:1,exp:'"Will" for predictions based on opinion. "I think" = belief → will.'},
        {q:'"I\'m hungry." — "___ get you something to eat."',opts:['I go','I will','I going to','I am going'],ans:1,exp:'Spontaneous decision = "will". No prior plan!'},
        {q:'Negative of "She will come":',opts:['She won\'t come.','She will not comes.','She doesn\'t will come.','She will not coming.'],ans:0,exp:'"Won\'t" = will + not. She won\'t come.'},
        {q:'"Will you help me?" — The correct answer is:',opts:['Yes, I will.','Yes, I do.','Yes, I am.','Yes, I shall.'],ans:0,exp:'Will → will. "Yes, I WILL." ✓'},
        {q:'Which sentence uses "will" CORRECTLY?',opts:['They will goes.','She will is here.','We will arrive soon.','He will can help.'],ans:2,exp:'"Will + base verb". "arrive" is base form. ✓'},
      ]},
      {id:'l9', title:'Going To', titlePt:'Going To', icon:'📅', xp:25, qs:[
        {q:'"Look at those clouds! It ___ rain."',opts:['will','is going to','rains','might'],ans:1,exp:'"Going to" for predictions with visible evidence.'},
        {q:'"We ___ visit grandma next weekend." (planned)',opts:['will','are going to','are going','going to'],ans:1,exp:'Pre-planned future = "be going to".'},
        {q:'Correct form: "She ___ study medicine."',opts:['is going to','are going to','is going','goes to'],ans:0,exp:'"She IS GOING TO study" — she + is + going to + base verb.'},
        {q:'What does "going to" express?',opts:['Spontaneous decisions','Prior plans and evidence','General facts','Habits'],ans:1,exp:'"Going to" = plans already made OR visible evidence of future event.'},
        {q:'"I ___ start exercising." (already decided)',opts:['am going to','will','should','might'],ans:0,exp:'"Going to" for plans already decided.'},
      ]},
    ]
  },

  // ══════════════════════════════════════════════════════
  //  UNIT 4 — VOCABULARY BUILDER
  // ══════════════════════════════════════════════════════
  {
    id:'u4', title:'Vocabulary Builder', titlePt:'Construtor de Vocabulário',
    desc:'Expand your word power! 💡',
    descPt:'Expande o teu vocabulário! 💡',
    color:'#00e676', icon:'📚', premium:false,
    lessons:[
      {id:'l10', title:'Common Adjectives', titlePt:'Adjectivos Comuns', icon:'🎨', xp:20, qs:[
        {q:'Which word means "very big"?',opts:['tiny','huge','narrow','shallow'],ans:1,exp:'"Huge" = extremely large. Opposite: "tiny".'},
        {q:'"The weather is very ___. I need a jacket."',opts:['hot','warm','cold','boiling'],ans:2,exp:'If you need a jacket, it\'s "cold"!'},
        {q:'"She is a ___ girl. She always helps others."',opts:['selfish','kind','rude','lazy'],ans:1,exp:'Someone who helps others is "kind".'},
        {q:'What does "expensive" mean?',opts:['Cheap','Costing a lot','Free','Beautiful'],ans:1,exp:'"Expensive" = high price. Opposite: "cheap".'},
        {q:'"The soup tastes ___." (very good)',opts:['disgusting','delicious','bland','salty'],ans:1,exp:'"Delicious" = very tasty. 😋'},
      ]},
      {id:'l11', title:'Everyday Actions', titlePt:'Acções do Dia-a-dia', icon:'🏃', xp:20, qs:[
        {q:'What do you do with a book?',opts:['eat','read','drive','cook'],ans:1,exp:'You "read" a book. 📖'},
        {q:'"I ___ breakfast every morning."',opts:['do','make','eat','drink'],ans:2,exp:'We "eat" breakfast.'},
        {q:'Where do you sleep?',opts:['In the kitchen','In the bathroom','In the garden','In the bedroom'],ans:3,exp:'You sleep in the bedroom!'},
        {q:'"Can you ___ the door, please? It\'s hot."',opts:['close','open','lock','break'],ans:1,exp:'If it\'s hot, you want to "open" the door!'},
        {q:'Which verb goes with "TV"?',opts:['watch','see','look','hear'],ans:0,exp:'We "watch" TV. 📺'},
      ]},
      {id:'l12', title:'Food & Cooking', titlePt:'Comida e Culinária', icon:'🍳', xp:25, qs:[
        {q:'What is the main ingredient in bread?',opts:['rice','flour','sugar','salt'],ans:1,exp:'Bread is made from "flour".'},
        {q:'"I need to ___ the vegetables before cooking."',opts:['wash','read','wear','build'],ans:0,exp:'You "wash" vegetables to clean them.'},
        {q:'Which cooking method uses water?',opts:['fry','bake','boil','grill'],ans:2,exp:'"Boil" = cooking in hot water.'},
        {q:'"This steak is too ___. I ordered it well-done."',opts:['cooked','raw','sweet','salty'],ans:1,exp:'"Raw" = not cooked.'},
        {q:'What does "spicy" mean?',opts:['Sweet taste','Hot burning taste','No taste','Sour taste'],ans:1,exp:'"Spicy" = hot flavour from chili/pepper.'},
      ]},
      {id:'l13', title:'Body Parts', titlePt:'Partes do Corpo', icon:'🦴', xp:20, qs:[
        {q:'"Head" means:',opts:['mão','pé','cabeça','nariz'],ans:2,exp:'head = cabeça. "Use your head!" means think!'},
        {q:'What is "hand" in Portuguese?',opts:['pé','mão','braço','dedo'],ans:1,exp:'hand = mão. "Give me your hand."'},
        {q:'Which body part do you use to SEE?',opts:['ears','nose','eyes','mouth'],ans:2,exp:'You see with your EYES! 👀'},
        {q:'Which body part do you use to HEAR?',opts:['eyes','ears','nose','tongue'],ans:1,exp:'You hear with your EARS! 👂'},
        {q:'"My ___ hurts." (pointing to leg)',opts:['arm','head','leg','finger'],ans:2,exp:'leg = perna. "My leg hurts."'},
      ]},
      {id:'l14', title:'Animals & Nature', titlePt:'Animais e Natureza', icon:'🦁', xp:20, qs:[
        {q:'What sound does a dog make?',opts:['meow','woof','moo','roar'],ans:1,exp:'Dogs go "woof"! 🐕 Cats go "meow".'},
        {q:'"Lion" in Portuguese is:',opts:['elefante','leão','girafa','crocodilo'],ans:1,exp:'lion = leão. Lions are symbols of Africa! 🦁'},
        {q:'Where do fish live?',opts:['in trees','in water','underground','in the sky'],ans:1,exp:'Fish live in water — rivers, lakes, oceans!'},
        {q:'Which animal is the biggest?',opts:['cat','dog','elephant','bird'],ans:2,exp:'The elephant is the biggest land animal on Earth!'},
        {q:'"Tree" means:',opts:['flor','erva','árvore','pedra'],ans:2,exp:'tree = árvore. Trees give us oxygen!'},
      ]},
    ]
  },

  // ══════════════════════════════════════════════════════
  //  UNIT 5 — DAILY LIFE & COMMUNICATION
  // ══════════════════════════════════════════════════════
  {
    id:'u5', title:'Daily Life', titlePt:'Vida Quotidiana',
    desc:'English for everyday situations 🌍',
    descPt:'Inglês para situações do dia-a-dia 🌍',
    color:'#ffd740', icon:'🌅', premium:false,
    lessons:[
      {id:'l15', title:'Days & Months', titlePt:'Dias e Meses', icon:'📅', xp:20, qs:[
        {q:'What is the first day of the week in English?',opts:['Monday','Sunday','Saturday','Wednesday'],ans:1,exp:'In English-speaking countries, Sunday is traditionally the first day of the week.'},
        {q:'"Segunda-feira" in English is:',opts:['Sunday','Monday','Tuesday','Wednesday'],ans:1,exp:'Monday = Segunda-feira. The week starts with Monday for most people!'},
        {q:'Which month comes after March?',opts:['February','May','April','June'],ans:2,exp:'March → April → May → June. April comes after March!'},
        {q:'"December" is the ___ month of the year.',opts:['10th','11th','12th','9th'],ans:2,exp:'December is the 12th and last month of the year!'},
        {q:'"Agosto" in English is:',opts:['June','July','August','September'],ans:2,exp:'August = Agosto. Summer month in Europe!'},
      ]},
      {id:'l16', title:'Telling the Time', titlePt:'Dizer as Horas', icon:'🕐', xp:20, qs:[
        {q:'"It is 3 o\'clock." This means:',opts:['3:15','3:00','3:30','2:45'],ans:1,exp:'"O\'clock" = exact hour. 3 o\'clock = 3:00.'},
        {q:'"Quarter past five" means:',opts:['5:05','5:10','5:15','5:45'],ans:2,exp:'"Quarter past" = 15 minutes after. Quarter past five = 5:15.'},
        {q:'"Half past eight" means:',opts:['8:00','8:15','8:30','8:45'],ans:2,exp:'"Half past" = 30 minutes. Half past eight = 8:30.'},
        {q:'How do you ask for the time?',opts:['Where is the time?','What is your time?','What time is it?','How much time?'],ans:2,exp:'"What time is it?" = Que horas são? The standard question!'},
        {q:'"It\'s midnight." This means:',opts:['12:00 PM','12:00 AM','6:00 AM','6:00 PM'],ans:1,exp:'"Midnight" = 12:00 AM = meia-noite. "Midday/noon" = 12:00 PM.'},
      ]},
      {id:'l17', title:'Shopping & Money', titlePt:'Compras e Dinheiro', icon:'🛍️', xp:25, qs:[
        {q:'"How much does it cost?" This question is about:',opts:['size','colour','price','quality'],ans:2,exp:'"How much does it cost?" = Quanto custa? Asking about the price!'},
        {q:'"It\'s too ___. I can\'t afford it."',opts:['cheap','expensive','free','small'],ans:1,exp:'"Expensive" = muito caro. "I can\'t afford it" = não consigo pagar.'},
        {q:'Where do you buy medicine?',opts:['supermarket','pharmacy','bakery','school'],ans:1,exp:'You buy medicine at a pharmacy (farmácia)!'},
        {q:'"Change" in a shop means:',opts:['a new item','the money you get back','a discount','the receipt'],ans:1,exp:'"Change" = the money the cashier gives you back after paying!'},
        {q:'"Can I help you?" is said by:',opts:['the customer','the security guard','the shop assistant','the manager'],ans:2,exp:'Shop assistants say "Can I help you?" when you enter a shop.'},
      ]},
      {id:'l18', title:'Directions & Places', titlePt:'Direcções e Lugares', icon:'🗺️', xp:25, qs:[
        {q:'"Turn left" means:',opts:['go straight','turn right','turn left','go back'],ans:2,exp:'"Turn left" = vira à esquerda. Opposite: "turn right" = vira à direita.'},
        {q:'Where do you go to catch a plane?',opts:['harbour','station','airport','bus stop'],ans:2,exp:'You catch a plane at the AIRPORT (aeroporto)!'},
        {q:'"It\'s next to the bank." This means:',opts:['far from','inside','beside/near','opposite'],ans:2,exp:'"Next to" = ao lado de. Beside/near the bank!'},
        {q:'How do you ask for directions?',opts:['Where is the bank?','Who is the bank?','When is the bank?','Why is the bank?'],ans:0,exp:'"Where is the bank?" = Onde fica o banco? Use "where" for location!'},
        {q:'"The hospital is ___ the park." (in front)',opts:['next to','behind','opposite','above'],ans:2,exp:'"Opposite" = in front of, facing. The hospital faces the park.'},
      ]},
    ]
  },

  // ══════════════════════════════════════════════════════
  //  UNIT 6 — PHRASAL VERBS (Premium)
  // ══════════════════════════════════════════════════════
  {
    id:'u6', title:'Phrasal Verbs', titlePt:'Verbos Frasais',
    desc:'Sound like a native speaker 🤯',
    descPt:'Soa como um falante nativo 🤯',
    color:'#bc8cff', icon:'💬', premium:true,
    lessons:[
      {id:'l19', title:'Common Phrasal Verbs', titlePt:'Verbos Frasais Comuns', icon:'💬', xp:30, qs:[
        {q:'"Give up" means:',opts:['to donate','to stop trying','to increase effort','to hand over'],ans:1,exp:'"Give up" = quit/desistir. "Don\'t give up!" 💪'},
        {q:'"She ran ___ her ex at the mall."',opts:['over','into','away','out'],ans:1,exp:'"Run into" = to meet unexpectedly. Awkward! 😬'},
        {q:'"Turn ___ the TV — I\'m sleeping!"',opts:['on','up','off','down'],ans:2,exp:'"Turn off" = stop a device.'},
        {q:'"He needs to ___ up with a good idea."',opts:['come','give','bring','look'],ans:0,exp:'"Come up with" = to think of/invent.'},
        {q:'"Can you ___ after my dog this weekend?"',opts:['look','watch','take','see'],ans:0,exp:'"Look after" = to take care of.'},
      ]},
    ]
  },

  // ══════════════════════════════════════════════════════
  //  UNIT 7 — IDIOMS (Premium)
  // ══════════════════════════════════════════════════════
  {
    id:'u7', title:'Idioms', titlePt:'Expressões Idiomáticas',
    desc:'Speak naturally & sound cool 😎',
    descPt:'Fala naturalmente e com estilo 😎',
    color:'#ff4081', icon:'🗣️', premium:true,
    lessons:[
      {id:'l20', title:'Common Idioms', titlePt:'Expressões Comuns', icon:'🗣️', xp:35, qs:[
        {q:'"It\'s raining cats and dogs." This means:',opts:['Animals are falling','It\'s raining heavily','The weather is strange','Pets are outside'],ans:1,exp:'"Raining cats and dogs" = raining VERY heavily.'},
        {q:'"Break a leg!" means:',opts:['Be careful!','Good luck!','Hurry up!','Don\'t be nervous!'],ans:1,exp:'"Break a leg" = good luck! Used in theatre.'},
        {q:'"He\'s on the fence about the decision." This means he is:',opts:['sitting down','undecided','very sure','wrong'],ans:1,exp:'"On the fence" = undecided/indeciso.'},
        {q:'"That exam was a piece of cake." This means:',opts:['It was delicious','It was very hard','It was very easy','It was boring'],ans:2,exp:'"A piece of cake" = very easy. 🎂'},
        {q:'"Hit the nail on the head" = to be:',opts:['violent','confused','exactly right','careless'],ans:2,exp:'"Hit the nail on the head" = exactly right/acertar em cheio.'},
      ]},
    ]
  },
];

const GRAM = [
  {id:'g1',cat:'Tenses',cc:'#2979ff',icon:'🔵',title:'Simple Present',sub:'Habits, facts & routines',
   formula:'Subject + V(s/es)',
   uses:['Habits: "She reads every day."','General truths: "Water boils at 100°C."','Fixed schedules: "The bus leaves at 8am."'],
   examples:[{en:'She works at a hospital.',pt:'Ela trabalha num hospital.'},{en:'Do you speak English?',pt:'Falas inglês?'},{en:'The Earth revolves around the Sun.',pt:'A Terra gira em torno do Sol.'}],
   signals:['always','usually','often','sometimes','rarely','never','every day','on Mondays'],
   tip:'💡 Add -s/-es for He/She/It: go→goes, watch→watches, study→studies',
   mistakes:[{w:'She go to school every day.',r:'She goes to school every day.'},{w:'He don\'t work on Sundays.',r:'He doesn\'t work on Sundays.'}],
   quiz:[{q:'Which is correct?',opts:['She go.','She goes.','She is go.','She going.'],ans:1},{q:'"He ___ like coffee."',opts:['don\'t','doesn\'t','not','isn\'t'],ans:1}]},
  {id:'g2',cat:'Tenses',cc:'#2979ff',icon:'🟡',title:'Present Continuous',sub:'Ongoing actions right now',
   formula:'Subject + am/is/are + V-ing',
   uses:['Actions happening NOW: "She is sleeping."','Temporary situations: "I\'m living in Maputo this year."','Future arrangements: "We are meeting tomorrow."','Annoying habits: "He\'s always interrupting!"'],
   examples:[{en:'I am studying English right now.',pt:'Estou a estudar inglês agora.'},{en:'Are you listening to me?',pt:'Estás a ouvir-me?'},{en:'They are building a new school.',pt:'Eles estão a construir uma escola.'}],
   signals:['now','right now','at the moment','currently','look!','listen!','today'],
   tip:'💡 Stative verbs can\'t use -ing: know, love, want, need, like, believe',
   mistakes:[{w:'She is know the answer.',r:'She knows the answer.'},{w:'I am wanting coffee.',r:'I want coffee.'}],
   quiz:[{q:'"Look! It ___ (rain)"',opts:['rains','rained','is raining','has rained'],ans:2},{q:'Which is WRONG?',opts:['I am eating.','She is running.','They are knowing.','We are waiting.'],ans:2}]},
  {id:'g3',cat:'Tenses',cc:'#2979ff',icon:'🟢',title:'Present Perfect',sub:'Past actions with present impact',
   formula:'Subject + have/has + Past Participle',
   uses:['Life experiences: "I have visited Paris."','Recent actions: "I have just eaten."','Unfinished periods: "She has lived here for 5 years."'],
   examples:[{en:'I have never eaten sushi.',pt:'Nunca comi sushi.'},{en:'She has already left.',pt:'Ela já foi embora.'},{en:'Have you finished your homework?',pt:'Já terminaste a tua tarefa?'}],
   signals:['just','already','yet','ever','never','recently','since','for','still'],
   tip:'💡 Simple Past with specific time: "I went yesterday." Present Perfect with no time or since/for.',
   mistakes:[{w:'I have went to the store.',r:'I have gone to the store.'},{w:'She has seen him yesterday.',r:'She saw him yesterday.'}],
   quiz:[{q:'"Have you ___ seen a lion?"',opts:['ever','just','since','yet'],ans:0},{q:'"She ___ just finished."',opts:['have','has','had','did'],ans:1}]},
  {id:'g4',cat:'Tenses',cc:'#2979ff',icon:'⏮️',title:'Simple Past',sub:'Completed past actions',
   formula:'Subject + V-ed / V2 (irregular)',
   uses:['Completed actions at specific time: "I ate at 7pm."','Sequence of events: "She woke up, had breakfast, then left."'],
   examples:[{en:'She walked to school yesterday.',pt:'Ela foi à escola a pé ontem.'},{en:'Did you see the match last night?',pt:'Viste o jogo ontem à noite?'},{en:'We bought a new car last year.',pt:'Comprámos um carro novo no ano passado.'}],
   signals:['yesterday','last week/month','ago','in 2010','when','then','once'],
   tip:'💡 Irregular verbs: go→went, buy→bought, eat→ate, see→saw, come→came',
   mistakes:[{w:'She goed to the shop.',r:'She went to the shop.'},{w:'Did you went there?',r:'Did you go there?'}],
   quiz:[{q:'"She ___ a letter." (write, past)',opts:['writed','wrote','has written','writing'],ans:1},{q:'"___ you see the game?"',opts:['Did','Do','Have','Were'],ans:0}]},
  {id:'g5',cat:'Modal Verbs',cc:'#d500f9',icon:'⚡',title:'Modal Verbs',sub:'can, should, must, might...',
   formula:'Subject + modal + base verb',
   uses:['CAN: ability — "I can swim."','SHOULD: advice — "You should sleep more."','MUST: obligation — "You must wear a seatbelt."','MIGHT/MAY: possibility — "It might rain."','WOULD: polite/conditional — "I would like a coffee."'],
   examples:[{en:'You should study more.',pt:'Deves estudar mais.'},{en:'She can speak three languages.',pt:'Ela consegue falar três línguas.'},{en:'It might snow tonight.',pt:'Pode nevar esta noite.'}],
   signals:['can','could','should','must','might','may','will','would','shall','ought to'],
   tip:'💡 Modals NEVER take -s for He/She/It: "She can swim" ✓ NOT "She cans swim" ✗',
   mistakes:[{w:'She cans speak French.',r:'She can speak French.'},{w:'You should to study.',r:'You should study.'}],
   quiz:[{q:'"You ___ see a doctor. You look terrible."',opts:['must to','should','can','might to'],ans:1},{q:'"She ___ swim when she was 5."',opts:['can','could','should','must'],ans:1}]},
  {id:'g6',cat:'Conditionals',cc:'#ff4081',icon:'🔀',title:'Conditionals',sub:'If this, then that',
   formula:'If + condition, result',
   uses:['Zero (always true): If + Present, Present','1st (real): If + Present, Will + base','2nd (unreal): If + Past, Would + base','3rd (past unreal): If + Past Perfect, Would have + PP'],
   examples:[{en:'If you heat ice, it melts.',pt:'Se aqueceres gelo, ele derrete.'},{en:'If I have time, I will call you.',pt:'Se tiver tempo, ligo-te.'},{en:'If I were rich, I would travel.',pt:'Se fosse rico, viajaria.'}],
   signals:['if','unless','provided that','as long as','in case'],
   tip:'💡 In 2nd Conditional, use "were" for all subjects: "If I WERE you..." (not "was").',
   mistakes:[{w:'If I will go, I will tell you.',r:'If I go, I will tell you.'},{w:'If I was you, I would leave.',r:'If I were you, I would leave.'}],
   quiz:[{q:'"If it rains, she ___ stay home."',opts:['would','will','stay','stayed'],ans:1},{q:'"If I were rich, I ___ travel."',opts:['will','would','am','should'],ans:1}]},
  {id:'g7',cat:'Articles',cc:'#1de9b6',icon:'📄',title:'Articles: A / An / The',sub:'The most confusing 3 words in English',
   formula:'A + consonant sound | An + vowel sound | The = specific',
   uses:['A/AN: first mention, not specific — "I saw a cat."','THE: specific/already mentioned — "The cat was orange."','THE: unique things — "the sun", "the moon"','ZERO article: languages, sports, meals — "She speaks English."'],
   examples:[{en:'She is a doctor.',pt:'Ela é médica.'},{en:'The doctor I like is Dr. Silva.',pt:'O médico de quem gosto é o Dr. Silva.'},{en:'He plays the piano.',pt:'Ele toca piano.'}],
   signals:['first mention→a/an','specific/known→the','unique→the','instruments→the'],
   tip:'💡 AN before vowel SOUNDS: "an hour" (h is silent!) / "a university" (sounds like "you"!)',
   mistakes:[{w:'She is a honest person.',r:'She is an honest person.'},{w:'I play a guitar.',r:'I play the guitar.'}],
   quiz:[{q:'Choose: "She is ___ engineer."',opts:['a','an','the','—'],ans:1},{q:'Choose: "___ Amazon is the largest river."',opts:['A','An','The','—'],ans:2}]},
  {id:'g8',cat:'Passive Voice',cc:'#ff6d00',icon:'🔄',title:'Passive Voice',sub:'The action matters, not the doer',
   formula:'Subject + be + Past Participle (+ by...)',
   uses:['When the doer is unknown: "The window was broken."','When the doer is obvious: "The thief was arrested."','In formal/academic writing.','To emphasise the result.'],
   examples:[{en:'The book was written by Couto.',pt:'O livro foi escrito pelo Couto.'},{en:'English is spoken worldwide.',pt:'O inglês é falado em todo o mundo.'},{en:'My phone was stolen!',pt:'O meu telefone foi roubado!'}],
   signals:['was/were + PP','is/are + PP','has been + PP','will be + PP'],
   tip:'💡 "By" introduces the agent (doer). Without "by" = unknown doer.',
   mistakes:[{w:'The cake was ate by him.',r:'The cake was eaten by him.'},{w:'It was writed in 2010.',r:'It was written in 2010.'}],
   quiz:[{q:'"The letter ___ yesterday." (write, passive)',opts:['wrote','was wrote','was written','is writing'],ans:2},{q:'Which is PASSIVE?',opts:['She cleaned the room.','The room was cleaned.','Cleaning the room.','She has cleaned it.'],ans:1}]},
];

// ─── PRONUNCIATION DATA ──────────────────────────────────
const PRON_WORDS = [
  {w:'Hello',ipa:'/həˈloʊ/',m:'A common greeting'},
  {w:'Pronunciation',ipa:'/prəˌnʌnsiˈeɪʃən/',m:'The way a word is spoken'},
  {w:'Beautiful',ipa:'/ˈbjuːtɪfl/',m:'Pleasing to the senses'},
  {w:'Comfortable',ipa:'/ˈkʌmftəbl/',m:'At ease; not tight'},
  {w:'Vocabulary',ipa:'/vəˈkæbjʊleri/',m:'All the words you know'},
  {w:'Wednesday',ipa:'/ˈwenzdeɪ/',m:'The middle day of the week'},
  {w:'February',ipa:'/ˈfebrʊeri/',m:'The second month'},
  {w:'Library',ipa:'/ˈlaɪbreri/',m:'A place with books'},
  {w:'Particularly',ipa:'/pəˈtɪkjʊləli/',m:'Especially; specifically'},
  {w:'Thoroughly',ipa:'/ˈθʌrəli/',m:'Completely; in detail'},
  {w:'Entrepreneur',ipa:'/ˌɒntrəprəˈnɜː/',m:'A business founder'},
  {w:'Vegetable',ipa:'/ˈvedʒtəbl/',m:'An edible plant'},
  {w:'Athlete',ipa:'/ˈæθliːt/',m:'A sports person'},
  {w:'Clothes',ipa:'/kloʊðz/',m:'What you wear'},
  {w:'Receipt',ipa:'/rɪˈsiːt/',m:'A proof of purchase'},
  {w:'Colonel',ipa:'/ˈkɜːnl/',m:'A military officer'},
  {w:'Worcestershire',ipa:'/ˈwʊstəʃɪə/',m:'A county in England'},
  {w:'Chaos',ipa:'/ˈkeɪɒs/',m:'Complete disorder'},
  {w:'Choir',ipa:'/ˈkwaɪər/',m:'A singing group'},
  {w:'Queue',ipa:'/kjuː/',m:'A line of waiting people'},
];

const MINIMAL_PAIRS = [
  {a:'Ship',b:'Sheep',pa:'/ʃɪp/',pb:'/ʃiːp/',note:'Short /ɪ/ vs Long /iː/ — a very common mistake!'},
  {a:'Bit',b:'Beat',pa:'/bɪt/',pb:'/biːt/',note:'Short /ɪ/ vs Long /iː/ — listen carefully'},
  {a:'Full',b:'Fool',pa:'/fʊl/',pb:'/fuːl/',note:'Short /ʊ/ vs Long /uː/'},
  {a:'Live',b:'Leave',pa:'/lɪv/',pb:'/liːv/',note:'Short /ɪ/ vs Long /iː/'},
  {a:'Think',b:'Sink',pa:'/θɪŋk/',pb:'/sɪŋk/',note:'The /θ/ vs /s/ — tongue between teeth!'},
  {a:'This',b:'Dis',pa:'/ðɪs/',pb:'/dɪs/',note:'The /ð/ (voiced) — tongue tip between teeth'},
  {a:'Wine',b:'Vine',pa:'/waɪn/',pb:'/vaɪn/',note:'/w/ vs /v/ — lips position matters!'},
  {a:'West',b:'Best',pa:'/west/',pb:'/best/',note:'/w/ vs /b/ — round lips for /w/'},
];

const TONGUE_TWISTERS = [
  {text:'She sells seashells by the seashore.',note:'Focus on /s/ vs /ʃ/ sounds'},
  {text:'Peter Piper picked a peck of pickled peppers.',note:'Perfect /p/ practise'},
  {text:'How much wood would a woodchuck chuck?',note:'Master the /w/ and /ʧ/ sounds'},
  {text:'The thirty-three thieves thought that they thrilled the throne.',note:'Pure /θ/ workout — go slow!'},
  {text:'Red lorry, yellow lorry, red lorry, yellow lorry.',note:'The dreaded /r/ and /l/ combo'},
  {text:'I scream, you scream, we all scream for ice cream.',note:'Fun vowel and consonant clusters'},
];

const DIFFICULT_SOUNDS = [
  {sound:'TH /θ/',eg:'think, three, throat, bath',tip:'Tongue TIP between upper and lower teeth. Blow air gently. NO vibration!',wrong:'Many say /t/ or /s/. E.g. "sink" instead of "think"'},
  {sound:'TH /ð/',eg:'this, that, the, breathe',tip:'Same position as /θ/ BUT add voice/vibration. Feel the buzz!',wrong:'Often said as /d/. E.g. "dis" instead of "this"'},
  {sound:'W /w/',eg:'wine, water, word, work',tip:'Round your lips like kissing. Start with /u/ then open. Short!',wrong:'Many say /v/. E.g. "vine" instead of "wine"'},
  {sound:'V /v/',eg:'very, voice, live, love',tip:'Top teeth on LOWER lip. Add vibration. Not just air!',wrong:'Often confused with /b/. E.g. "berry" instead of "very"'},
  {sound:'H /h/',eg:'hello, happy, hold, have',tip:'Just breathe out. No vibration. Light and breezy! No sound at all before the vowel.',wrong:'Many drop the H. E.g. "ello" instead of "hello"'},
  {sound:'R /r/',eg:'red, right, run, drive',tip:'Tongue tip raised, not touching anything. Curl back slightly. Lips rounded.',wrong:'Do not trill like Spanish R. English R is smooth.'},
];

// ─── WORD SCRAMBLE DATA ──────────────────────────────────
const WORDS_FOR_GAME = [
  // ── BEGINNER TIER (3–5 letters) — for first-time players ──
  {w:'CAT',h:'A small furry animal that says meow'},
  {w:'DOG',h:'A loyal pet that says woof'},
  {w:'SUN',h:'The big star that gives us light and heat'},
  {w:'RED',h:'The colour of fire and blood'},
  {w:'BIG',h:'Something that is large in size'},
  {w:'RUN',h:'To move your legs fast'},
  {w:'EAT',h:'To put food in your mouth'},
  {w:'HOT',h:'Having a high temperature'},
  {w:'COLD',h:'Having a low temperature'},
  {w:'HAND',h:'The body part at the end of your arm'},
  {w:'FACE',h:'The front of your head, with eyes and mouth'},
  {w:'BOOK',h:'Pages with words and pictures that you read'},
  {w:'TREE',h:'A tall plant with a trunk and leaves'},
  {w:'FISH',h:'An animal that lives in water'},
  {w:'BLUE',h:'The colour of the sky and ocean'},
  {w:'RAIN',h:'Water that falls from clouds'},
  {w:'MILK',h:'A white drink that comes from cows'},
  {w:'BIRD',h:'An animal with wings and feathers that can fly'},
  {w:'JUMP',h:'To push yourself off the ground into the air'},
  {w:'SING',h:'To make music with your voice'},
  {w:'OPEN',h:'Not closed; to allow entry'},
  {w:'LOVE',h:'A deep feeling of affection'},
  {w:'FIRE',h:'Hot, bright flames from burning'},
  {w:'STAR',h:'A bright light you see in the sky at night'},
  // ── INTERMEDIATE TIER (6–8 letters) ──
  {w:'SCHOOL',h:'A place where children go to learn'},
  {w:'FAMILY',h:'Parents, children, brothers and sisters'},
  {w:'FRIEND',h:'A person you like and trust'},
  {w:'ORANGE',h:'A round fruit, also a warm colour between red and yellow'},
  {w:'FLOWER',h:'The colourful part of a plant'},
  {w:'DINNER',h:'The main meal of the day, usually in the evening'},
  {w:'WINDOW',h:'A glass opening in a wall that lets in light'},
  {w:'MARKET',h:'A place where people buy and sell things'},
  {w:'TRAVEL',h:'To go from one place to another'},
  {w:'STRONG',h:'Having great power or physical force'},
  {w:'SIMPLE',h:'Easy to understand; not complicated'},
  {w:'LISTEN',h:'To pay attention to sounds'},
  {w:'MOTHER',h:'A female parent'},
  {w:'FATHER',h:'A male parent'},
  {w:'SISTER',h:'A female sibling'},
  {w:'BROTHER',h:'A male sibling'},
  {w:'DOCTOR',h:'A person trained to treat sick people'},
  {w:'FINGER',h:'One of the five parts at the end of your hand'},
  {w:'HUNGRY',h:'Feeling a need to eat food'},
  {w:'HAPPY',h:'Feeling pleasure and joy'},
  // ── ADVANCED TIER (9+ letters) — original words ──
  {w:'BEAUTIFUL',h:'An adjective meaning very attractive'},
  {w:'VOCABULARY',h:'All the words a person knows'},
  {w:'GRAMMAR',h:'Rules for using a language correctly'},
  {w:'PRONUNCIATION',h:'How you say a word'},
  {w:'FLUENCY',h:'Ability to speak easily and accurately'},
  {w:'PRACTICE',h:'Repeated exercise to improve skill'},
  {w:'LANGUAGE',h:'A system of communication'},
  {w:'SENTENCE',h:'A group of words expressing a complete thought'},
  {w:'ADJECTIVE',h:'A word that describes a noun'},
  {w:'PREPOSITION',h:'A word showing relationship (in, on, at)'},
  {w:'CONJUNCTION',h:'A word that joins (and, but, or)'},
  {w:'IRREGULAR',h:'Not following the normal rules'},
  {w:'CONTINUOUS',h:'Without stopping; still happening'},
  {w:'PERFECT',h:'Without errors; complete'},
  {w:'PASSIVE',h:'Receiving the action, not doing it'},
  {w:'CHALLENGE',h:'Something difficult to do'},
  {w:'ACHIEVEMENT',h:'A thing accomplished successfully'},
  {w:'CONFIDENT',h:'Feeling sure about yourself'},
  {w:'EXCELLENT',h:'Extremely good; outstanding'},
  {w:'IMPORTANT',h:'Of great significance or value'},
  {w:'COMMUNICATE',h:'To share information with others'},
  {w:'TRANSLATE',h:'To express in another language'},
  {w:'INTERPRET',h:'To explain the meaning of something'},
  {w:'EDUCATION',h:'The process of learning and teaching'},
];

// ─── AI CHAT DATA ────────────────────────────────────────
const AI_QUICK_PROMPTS = {
  en: [
    {text: "Difference between 'since' and 'for'?", icon: '⏱️'},
    {text: "How do I use 'the' correctly?", icon: '📖'},
    {text: "Explain Present Perfect simply", icon: '✅'},
    {text: "Common phrasal verbs with 'get'", icon: '💬'},
    {text: "How to pronounce 'th' sounds?", icon: '🔊'},
    {text: "Give me 5 useful English idioms", icon: '🗣️'},
    {text: "Will vs Going To — what's the difference?", icon: '🔮'},
    {text: "How to avoid common Mozambican English errors?", icon: '🇲🇿'},
  ],
  pt: [
    {text: "Diferença entre 'since' e 'for'?", icon: '⏱️'},
    {text: "Como usar 'the' correctamente?", icon: '📖'},
    {text: "Explica o Presente Perfeito de forma simples", icon: '✅'},
    {text: "Verbos frasais comuns com 'get'", icon: '💬'},
    {text: "Como pronunciar os sons 'th'?", icon: '🔊'},
    {text: "Dá-me 5 expressões inglesas úteis", icon: '🗣️'},
    {text: "Will vs Going To — qual é a diferença?", icon: '🔮'},
    {text: "Erros de inglês comuns em Moçambique?", icon: '🇲🇿'},
  ]
};

const AI_RESPONSES = {
  default: {
    en: [
      "Great question! Let me break this down for you step by step...",
      "This is a common confusion for learners! Here's how to think about it:",
      "As your English tutor, I'd say the key thing to remember is:",
      "Excellent! This is exactly the kind of thing that makes the difference between good and fluent English:",
    ],
    pt: [
      "Boa pergunta! Vou explicar passo a passo...",
      "Esta é uma confusão comum para estudantes! Aqui está como pensar nisso:",
      "Como teu tutor de inglês, diria que a coisa principal a lembrar é:",
      "Excelente! Isto é exactamente o tipo de coisa que faz a diferença entre o bom e o inglês fluente:",
    ]
  },
  since_for: {
    en: `**Since vs For** ⏱️\n\n📌 **FOR** = duration (how long)\n→ "I have studied English **for** 2 years."\n→ "She has been waiting **for** an hour."\n\n📌 **SINCE** = starting point (from when)\n→ "I have studied English **since** 2022."\n→ "She has been waiting **since** 3pm."\n\n💡 **Trick**: Replace with "during X time" (FOR) vs "from that point" (SINCE).\n\nFOR = a span ↔ SINCE = a point in time 🎯`,
    pt: `**Since vs For** ⏱️\n\n📌 **FOR** = duração (quanto tempo)\n→ "Estudo inglês **for** 2 anos."\n→ "Ela está à espera **for** uma hora."\n\n📌 **SINCE** = ponto de partida (desde quando)\n→ "Estudo inglês **since** 2022."\n→ "Ela está à espera **since** às 15h."\n\n💡 **Truque**: Substitui por "durante X tempo" (FOR) vs "desde aquele ponto" (SINCE).\n\nFOR = período ↔ SINCE = ponto no tempo 🎯`
  },
};

// ─── ABOUT ME DATA ───────────────────────────────────────
const ABOUT_DATA = {
  name: 'Sebastiao Zefanias Nhamuneque Junior',
  nickname: 'Sebastian',
  role: {en: 'English Teacher · Translator · Interpreter', pt: 'Professor de Inglês · Tradutor · Intérprete'},
  location: 'Maputo / Matola, Mozambique 🇲🇿',
  email: 'nhamoneques@gmail.com',
  phone: '+258 845 713 020',
  whatsapp: '+258845713020',
  education: [
    {
      en: {degree: 'Bachelor\'s in Translation & Interpretation', school: 'Universidade Eduardo Mondlane', year: '2022–Present', note: 'Final Year Student'},
      pt: {degree: 'Licenciatura em Tradução e Interpretação', school: 'Universidade Eduardo Mondlane', year: '2022–Presente', note: 'Estudante do Último Ano'}
    }
  ],
  experience: [
    {
      en: {title: 'English Teacher', org: 'CLCI — Consultoria Linguística e Coaching Isac', period: '2020–2024', desc: 'Taught English levels 1 through 4 to diverse groups of adult learners. Developed custom lesson plans and assessment tools.'},
      pt: {title: 'Professor de Inglês', org: 'CLCI — Consultoria Linguística e Coaching Isac', period: '2020–2024', desc: 'Leccionou inglês dos níveis 1 ao 4 a grupos diversificados. Desenvolveu planos de aula e ferramentas de avaliação personalizadas.'}
    },
    {
      en: {title: 'Translator EN↔PT', org: 'Freelance', period: '2022–Present', desc: 'Technical and academic translation services. Specialisation in education, linguistics, and development sector documents.'},
      pt: {title: 'Tradutor EN↔PT', org: 'Freelancer', period: '2022–Presente', desc: 'Serviços de tradução técnica e académica. Especialização em educação, linguística e documentos do sector do desenvolvimento.'}
    }
  ],
  skills: [
    {icon:'🎓', en:'English Teaching', pt:'Ensino de Inglês'},
    {icon:'📝', en:'Translation (EN↔PT)', pt:'Tradução (EN↔PT)'},
    {icon:'🎙️', en:'Consecutive Interpretation', pt:'Interpretação Consecutiva'},
    {icon:'🌍', en:'Localisation', pt:'Localização'},
    {icon:'📱', en:'Educational Technology', pt:'Tecnologia Educacional'},
    {icon:'💻', en:'Basic IT Skills', pt:'Informática Básica'},
    {icon:'🗣️', en:'Content Creation', pt:'Criação de Conteúdo'},
    {icon:'📊', en:'Language Assessment', pt:'Avaliação Linguística'},
  ],
  stats: [
    {n: 4, en: 'Years Teaching', pt: 'Anos de Ensino', icon: '🎓'},
    {n: 200, en: 'Students Taught', pt: 'Estudantes', icon: '👥'},
    {n: 3, en: 'Languages', pt: 'Línguas', icon: '🌍'},
    {n: 50, en: 'Lessons Created', pt: 'Lições Criadas', icon: '📚'},
  ],
  socials: {
    facebook: '#', instagram: 'https://instagram.com', tiktok: '#',
    linkedin: '#', youtube: '#', github: '#'
  }
};

// ─── SEARCH INDEX ────────────────────────────────────────
const buildSearchIndex = () => {
  const idx = [];
  UNITS.forEach(unit => {
    unit.lessons.forEach(l => {
      idx.push({
        title: l.title, sub: `${unit.title} · +${l.xp} XP`,
        icon: l.icon, tag: 'Lesson', tagColor: unit.color,
        action: () => window.startLesson && window.startLesson(unit.id, l.id)
      });
    });
  });
  GRAM.forEach(g => {
    idx.push({
      title: g.title, sub: g.sub,
      icon: g.icon, tag: g.cat, tagColor: g.cc,
      action: () => {
        if (window.goTabFn) window.goTabFn('grammar');
        setTimeout(() => { const el = document.getElementById('gc-'+g.id); if(el) el.scrollIntoView({behavior:'smooth'}); }, 300);
      }
    });
  });
  PRON_WORDS.forEach(p => {
    idx.push({
      title: p.w, sub: `${p.ipa} · ${p.m}`,
      icon: '🔊', tag: 'Sound', tagColor: '#1de9b6',
      action: () => { if (window.goTabFn) window.goTabFn('sounds'); }
    });
  });
  return idx;
};

// Explicit window export so app.js can call window.buildSearchIndex() safely,
// even if this file is ever converted to type="module".
window.buildSearchIndex = buildSearchIndex;
